-- 밈 콘텐츠 일괄 적용 — 전체 복붙 후 Supabase SQL Editor에서 Run.
-- 여러 번 실행해도 안전(idempotent). id 자동생성 전환 + name 유니크 + 10개 채우기 + 신규 2개.

-- ═══ 0) memes.id 자동생성(identity) 전환 — id 없는 INSERT 허용 (이미 됐으면 건너뜀) ═══
do $$
begin
  if (select is_identity from information_schema.columns
      where table_schema='public' and table_name='memes' and column_name='id') = 'NO' then
    execute 'alter table memes alter column id add generated by default as identity';
    perform setval(pg_get_serial_sequence('memes','id'), (select max(id) from memes));
  end if;
end $$;

-- ═══ 1) name 유니크 제약 (on conflict 용, 이미 있으면 건너뜀) ═══
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'memes_name_unique') then
    alter table memes add constraint memes_name_unique unique (name);
  end if;
end $$;

-- ═══ 2) 기존 10개 채우기 ═══
update memes set
  description = '유튜브 "낭만부부" 콘텐츠에서 모란시장 머릿고기 식당 사장님이 만족을 표할 때 쓴 말투. 손가락 이모지를 붙여 소소한 긍정을 표현한다. 점심 메뉴가 마음에 들 때, 칼퇴 확정됐을 때 손가락만 펴면 된다. 유튜브 코리아가 "2026년 첫 밈"으로 언급했다.',
  tags = array['#긍정','#리액션','#이모지','#유튜브','#2026신상'],
  status = 'new', category = '방송인', source = 'https://somako.co.kr/', photo_url = null
where id = 1;  -- 좋다 이모지

update memes set
  description = '인스타 크리에이터 오상추가 "2026년 유행어 배포합니다"라며 릴스로 선포한 말. "난리 났다"의 변형으로 놀라거나 호들갑 떨 때 쓴다. "[감정]+자베스" 구조라 슬프자베스·행복자베스로 무한 응용된다. 배포한다더니 진짜로 다들 가져다 썼다.',
  tags = array['#유행어','#릴스','#인스타','#응용가능','#2026신상'],
  status = 'new', category = '크리에이터', source = 'https://oflouis.dev/trends/trending-memes-2026-h1/', photo_url = null
where id = 2;  -- 난리자베스

update memes set
  description = '유튜버 카니가 한국어 형용사를 외우려고 만든 암기송. "매끈매끈하다 매끈매끈한, 평평하다 평평한"처럼 반복하는 리듬에 즉석 안무가 더해지며 폭발했다. 중독성 있는 반복 구조가 핵심.',
  tags = array['#숏폼','#챌린지','#중독성','#노래','#외국인'],
  status = 'new', category = '크리에이터', source = 'https://gogumafarm.kr/', photo_url = null
where id = 3;  -- 매끈매끈하다

update memes set
  description = '"매끈매끈하다" 리듬을 그대로 차용해 새 유행어를 얹은 리메이크. 후속 영상에서 "샤갈은 기분 나쁠 때, 야르는 기분 좋을 때"라며 뜻을 소개했다. 밈이 밈을 낳은 사례.',
  tags = array['#숏폼','#리메이크','#유행어','#중독성','#파생밈'],
  status = 'new', category = '크리에이터', source = 'https://somako.co.kr/', photo_url = null
where id = 4;  -- 샤갈 야르 아자스

update memes set
  description = '2023년 카카오톡 대화가 원조. "다음 얘기가 궁금하면 냐냐냥!!! 입력하세요"라고 보냈더니 상대가 진짜로 "냐냐냥"을 보낸 순수한 반응이 화제가 됐다. 2026년 3월 X·인스타·브랜드 계정까지 전 플랫폼에서 재유행했다.',
  tags = array['#카톡','#부활밈','#순수함','#커뮤니티발'],
  status = 'steady', category = '일반인', source = 'https://letter.wepick.kr/post/23942', photo_url = null
where id = 5;  -- 냐냐냥

update memes set
  description = '최강록의 유튜브 영상을 "불안형 여친과 안정형 남친" 비유로 편집한 쇼츠에서 시작. 애착유형 담론에 최강록 특유의 덤덤하고 안정적인 말투가 얹히며 퍼졌다.',
  tags = array['#애착유형','#쇼츠','#연애','#최강록','#2026신상'],
  status = 'new', category = '방송인', source = 'https://theqoo.net/square/4076626473', photo_url = null
where id = 6;  -- 안정형 남친

update memes set
  description = '일본인 썸남에게 받은 "갑차기스러운데 고백 취소해도 돼?"라는 메시지가 X에서 화제가 되며 퍼진 밈. 어눌한 한국어가 주는 어이없음이 포인트.',
  tags = array['#X','#연애','#어눌한한국어','#커뮤니티발'],
  status = 'new', category = '일반인', source = 'https://www.openads.co.kr/content/contentDetail?contsId=17740', photo_url = null
where id = 7;  -- 갑차기스러운데

update memes set
  description = '어떤 상황에서도 골반 춤은 멈추지 않는다는 콘셉트. 뭐랭하맨, 햄깅 등 여러 크리에이터가 패러디하며 퍼졌다.',
  tags = array['#춤','#숏폼','#패러디','#중독성'],
  status = 'new', category = '크리에이터', source = 'https://www.openads.co.kr/content/contentDetail?contsId=17740', photo_url = null
where id = 8;  -- 골반통신

update memes set
  description = '라인프렌즈 캐릭터 이름. "못생겼다"는 말을 직접 하는 대신 돌려 쓰는 표현으로 자리잡았다.',
  tags = array['#캐릭터','#디스','#라인프렌즈','#돌려까기'],
  status = 'new', category = '캐릭터', source = 'https://adure.net/', photo_url = null
where id = 9;  -- 밤티

update memes set
  description = '최강록이 요리 서바이벌에서 쓴 말투에서 시작. "A, 그런데 이제 B를 곁들인" 형태로 앞말에 사족을 덧붙일 때 쓴다. 본인이 누구보다 잘 써먹는 것으로도 유명하다. 수년째 살아남은 대표적인 스테디 밈.',
  tags = array['#흑백요리사','#말투','#장수밈','#최강록','#응용가능'],
  status = 'steady', category = '방송인', source = 'https://namu.wiki/w/최강록/미디어 활동', photo_url = null
where id = 10; -- 그런데 이제

-- ═══ 3) 신규 추가 ═══
-- 영크크 (검증 완료)
insert into memes (name, keywords, description, tags, status, category, source, photo_url)
values (
  '영크크',
  array['영크크','늙크크','올크크'],
  '보이그룹 코르티스(CORTIS)의 곡 〈YOUNGCREATORCREW〉 제목을 줄인 말. 원뜻은 "젊은 창작자 무리"지만, 지금은 "요즘 감성이다", "트렌디하다"는 뜻으로 쓰인다. 반대말로 늙크크·올크크(Old Creator Crew)가 생겨나, 2030 직장인들이 "나는 이제 영크크 아니고 늙크크야"라며 자학 유머로 쓰면서 더 퍼졌다. 2026년 2월 곡 선공개 때 K팝 팬덤에서 시작해 예능 "냉장고를 부탁해" 자막에까지 등장하며 대중화됐다. "크크"라는 발음이 웃음소리 ㅋㅋ를 연상시켜 어감 자체가 재미의 핵심이다.',
  array['#K팝','#코르티스','#세대드립','#자학개그','#어감밈','#늙크크'],
  'new', '가수', 'https://namu.wiki/w/영크크', null
)
on conflict (name) do nothing;

-- 아바라 (⚠️ 밈 맥락 미확인 — description/tags는 확인 후 직접 채우세요)
insert into memes (name, keywords, description, tags, status, category, source, photo_url)
values (
  '아바라',
  array['아바라'],
  '',            -- ⚠️ 직접 작성
  array['#'],    -- ⚠️ 직접 작성
  'new', '기타', null, null
)
on conflict (name) do nothing;

-- ═══ 4) 확인 ═══
-- select id, name, status, category, tags, description from memes order by id;
-- select id, name from memes where description = '' or description is null;  -- 미완성 목록
