-- memes.id 를 자동생성(identity)으로 전환 — 콘텐츠 채우기 스크립트의 INSERT가 id 없이 동작하게.
-- 기존 명시적 id(1~10)는 그대로 두고, 앞으로 INSERT 시 id를 생략하면 자동 부여된다.
-- ★ 한 번만 실행하면 된다. (SQL Editor에서 Run)

-- 1) id 컬럼에 identity 부여 (by default = 명시적 id도 계속 허용)
alter table memes alter column id add generated by default as identity;

-- 2) 자동 시퀀스를 현재 최대 id 다음으로 맞춰 기존 행과 충돌 방지
select setval(pg_get_serial_sequence('memes','id'), (select max(id) from memes));

-- 확인: 이후 아래처럼 id 없이 INSERT 하면 11, 12 … 로 자동 부여됨
-- insert into memes (name, keywords, status) values ('테스트', array['테스트'], 'new');
