-- 미국 인터넷 밈 시드 데이터 (신규 400개, 기존 100개와 중복 없음)
-- 출처: Know Your Meme, Imgflip(top all-time templates), Wikipedia(Italian brainrot),
--       NBC News, FOX, tjTODAY 등 검증 기반. photo_url은 자체 호스팅 위해 null.

insert into memes (name, keywords, description, tags, status, category, source, photo_url) values
('Left Exit 12 Off Ramp',
 array['left exit 12','급커브 차량','exit 12'],
 '고속도로 본선 대신 급하게 출구 램프로 꺾어 들어가는 차 사진. 원래 하던 것 대신 엉뚱하고 솔깃한 선택으로 급선회할 때 쓰는 라벨링 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('UNO Draw 25 Cards',
 array['uno draw 25','우노 25장','카드 뽑기'],
 '우노 게임에서 "규칙을 지키거나 25장을 뽑아라" 선택지 앞에서 차라리 25장을 집어 드는 밈. 간단한 일도 죽어도 안 하려는 고집을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Running Away Balloon',
 array['running away balloon','도망가는 풍선','놓친 풍선'],
 '한 사람이 풍선을 붙잡으려 하지만 다른 유혹이 풍선을 놓게 만드는 라벨링 밈. 좋은 것을 알면서도 놓치게 만드는 방해 요소를 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Boardroom Meeting Suggestion',
 array['boardroom meeting','회의실 제안','창밖으로 던지기'],
 '임원 회의에서 좋은 아이디어를 낸 사람을 창밖으로 던져버리는 4컷 밈. 마지막 엉뚱한 발언이 화를 부르는 구조.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('X X Everywhere',
 array['x everywhere','buzz lightyear','토이스토리 버즈'],
 '버즈가 우디에게 팔을 두르며 "X, X가 사방에 있어"라 말하는 토이스토리 장면 템플릿. 무언가가 도처에 널렸음을 강조.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Epic Handshake',
 array['epic handshake','우람한 악수','프레데터 악수'],
 '두 팔뚝이 억세게 맞잡는 프레데터 영화 장면. 서로 달라 보이는 둘이 사실 같은 지점에서 합의할 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Sad Pablo Escobar',
 array['sad pablo escobar','쓸쓸한 파블로','기다리는 에스코바르'],
 '드라마 나르코스의 파블로 에스코바르가 홀로 쓸쓸히 앉아 기다리는 장면. 외롭고 지루하게 무언가를 기다릴 때의 심정을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Inhaling Seagull',
 array['inhaling seagull','숨 들이쉬는 갈매기','aaaa 갈매기'],
 '고개를 들고 크게 숨을 들이마시는 갈매기 사진. 무언가를 외치기 직전 한껏 숨을 들이켜는 순간을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('The Scroll Of Truth',
 array['scroll of truth','진실의 두루마리','싫어 개'],
 '오랜 탐험 끝에 진실이 적힌 두루마리를 펼쳐 보고는 "싫어"라며 던져버리는 만화. 인정하기 싫은 진실을 마주할 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Monkey Puppet',
 array['monkey puppet','곁눈질 원숭이','awkward monkey'],
 '일본 어린이 프로의 원숭이 인형이 어색하게 옆을 흘깃 보는 장면. 뜨끔하거나 민망한 상황에서 딴청 피우는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('The Rock Driving',
 array['the rock driving','돌아보는 더 락','운전하는 드웨인'],
 '드웨인 존슨이 운전하다 걱정스러운 얼굴로 옆을 홱 돌아보는 2컷. 상대 말에 어이없어하거나 당황하는 반응을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Y''all Got Any More Of That',
 array['yall got any more','중독된 표정','tyrone biggums'],
 '데이브 셔펠의 캐릭터가 갈망하는 표정으로 "그거 더 없어?"라고 조르는 장면. 무언가에 몹시 목말라 하는 심정을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Marked Safe From',
 array['marked safe from','안전 표시','페이스북 안전확인'],
 '페이스북 재난 안전확인 화면을 흉내 내 "오늘 나는 X로부터 안전함이 확인됨"이라 적는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('The Most Interesting Man In The World',
 array['most interesting man','dos equis','가장 흥미로운 남자'],
 '도스 에키스 맥주 광고 신사가 "나는 늘 X하진 않지만, 한다면 이렇게"라며 여유롭게 말하는 템플릿.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Oprah You Get A',
 array['oprah you get a','오프라 다 줄게','you get a car'],
 '오프라 윈프리가 "당신도 받고, 당신도 받고, 모두가 받아요!"라 외치며 마구 나눠주는 장면.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Third World Skeptical Kid',
 array['skeptical kid','의심하는 아이','제3세계 아이'],
 '한쪽 눈썹을 치켜올린 아이의 의심 어린 표정. 앞뒤 안 맞는 논리를 들었을 때의 회의감을 표현하는 어드바이스 애니멀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('American Chopper Argument',
 array['american chopper','오렌지카운티 논쟁','고함치는 부자'],
 '리얼리티쇼 아메리칸 초퍼에서 부자(父子)가 삿대질하며 언쟁하는 5컷. 스스로와 벌이는 논쟁을 단계별로 풀어낼 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('They''re The Same Picture',
 array['theyre the same picture','똑같은 사진','the office pam'],
 '더 오피스에서 팸이 두 사진을 비교하라 하자 "이거 둘 다 같은 사진인데요"라 답하는 장면. 사실상 똑같은 두 대상을 비꼴 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('I Bet He''s Thinking About Other Women',
 array['thinking about other women','딴 여자 생각','침대 커플'],
 '침대에서 여자가 "쟤는 지금 다른 여자 생각하겠지"라 걱정하지만, 남자는 전혀 엉뚱한 걸 골똘히 생각하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('First World Problems',
 array['first world problems','선진국 고민','우는 여자'],
 '울고 있는 여자 사진에 사소하고 배부른 고민을 적는 밈. 별것 아닌 불편을 심각한 척 토로할 때 씀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Trump Bill Signing',
 array['trump bill signing','서명 들어보이기','행정명령 보여주기'],
 '트럼프가 서명한 문서를 카메라에 들어 보이는 사진. 문서 내용을 엉뚱한 문구로 바꿔 넣는 라벨링 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('This Is Where I''d Put My Trophy If I Had One',
 array['trophy if i had one','트로피 자리','텅 빈 진열장'],
 '만화 캐릭터가 빈 진열장을 가리키며 "트로피가 있었다면 여기 뒀을 텐데"라 말하는 장면. 없는 성과를 자조할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Unsettled Tom',
 array['unsettled tom','불안한 톰','의심하는 톰'],
 '톰과 제리의 톰이 억지 미소 뒤로 불안하게 곁눈질하는 장면. 뭔가 미심쩍고 불편한 순간을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Anakin Padme 4 Panel',
 array['anakin padme','for the better right','더 나아지는 거지?'],
 '스타워즈 아나킨이 무언가를 선언하고 파드메가 웃으며 "더 좋아지는 거지?"라 묻지만 답이 없는 4컷. 불길한 침묵을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Star Wars Yoda',
 array['star wars yoda','요다','do or do not'],
 '요다가 도치된 어순으로 격언을 말하는 템플릿. 어순을 뒤바꿔 그럴듯한 지혜를 흉내 낼 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Bike Fall',
 array['bike fall','막대기 자전거','자기 발등 찍기'],
 '자전거 바퀴에 스스로 막대기를 꽂아 넘어지고는 남 탓하는 3컷 만화. 자업자득 상황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Who Killed Hannibal',
 array['who killed hannibal','한니발 누가 죽였어','에릭 안드레 총'],
 '에릭 안드레가 옆 사람을 총으로 쏘고는 "누가 이랬어?"라 시치미 떼는 장면. 자기가 저질러 놓고 모른 척할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('That Would Be Great',
 array['that would be great','office space','롬버그 그럼 좋겠네'],
 '영화 오피스 스페이스의 상사 롬버그가 커피잔을 들고 "그래 주면 정말 좋겠는데"라 은근히 압박하는 장면.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Brace Yourselves X Is Coming',
 array['brace yourselves','각오해라','네드 스타크'],
 '왕좌의 게임 네드 스타크가 "각오해라, X가 온다"라 경고하는 템플릿. 곧 닥칠 일에 대비하라는 뉘앙스.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Spongebob Ight Imma Head Out',
 array['ight imma head out','이만 가볼게','패트릭 일어남'],
 '스폰지밥의 패트릭이 소파에서 벌떡 일어나며 "그럼 난 이만" 하는 장면. 불편해져서 자리를 뜨고 싶을 때 씀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Clown Applying Makeup',
 array['clown makeup','광대 분장','점점 광대되기'],
 '얼굴에 광대 분장을 단계별로 완성해가는 4컷. 스스로 점점 더 바보 같은 결론에 도달하는 과정을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('But That''s None Of My Business',
 array['none of my business','케르밋 차','상관없지만'],
 '케르밋이 립톤 차를 홀짝이며 "근데 뭐, 내 알 바 아니지"라 능청 떠는 장면. 은근히 지적하고 빠질 때 씀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Creepy Condescending Wonka',
 array['condescending wonka','진 와일더 윌리 웡카','비꼬는 웡카'],
 '윌리 웡카(진 와일더)가 턱을 괴고 능글맞게 웃는 장면. "오 그래? 대단하네" 식으로 비아냥댈 때 쓰는 템플릿.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('X All The Y',
 array['x all the y','allie brosh','다 해버려'],
 '막대기 인간이 팔을 치켜들고 "모든 Y를 X하자!"라 외치는 그림. 의욕 넘치게 뭔가를 다 해치우려는 태도를 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Don''t You Squidward',
 array['dont you squidward','스퀴드워드 창문','부러운 징징이'],
 '스폰지밥의 징징이가 창밖에서 노는 둘을 부럽게 바라보는 장면. 소외감이나 부러움을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Laughing Leo',
 array['laughing leo','웃는 레오','장고 디카프리오'],
 '장고에서 디카프리오가 술잔을 들고 크게 웃는 장면. 통쾌하거나 남을 비웃을 때 쓰는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Sleeping Shaq',
 array['sleeping shaq','자다 깬 샤크','무관심 vs 관심'],
 '샤킬 오닐이 한쪽에선 잠들고 다른 쪽에선 번쩍 깨어나는 2컷. 무엇에 무관심하고 무엇에 열광하는지 비교.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Captain Picard Facepalm',
 array['picard facepalm','페이스팜','스타트렉 얼굴 감싸기'],
 '스타트렉 피카드 함장이 손으로 얼굴을 감싸는 장면. 어이없고 한심한 상황에 대한 실망을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Philosoraptor',
 array['philosoraptor','철학 공룡','랩터 사색'],
 '발톱을 턱에 괸 벨로시랩터 그림. 그럴듯하지만 실없는 철학적 질문을 던질 때 쓰는 고전 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'character', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Matrix Morpheus',
 array['matrix morpheus','모피어스','what if i told you'],
 '매트릭스의 모피어스가 "내가 만약 이렇게 말한다면?"이라 운을 떼는 장면. 통념을 뒤집는 사실을 밝힐 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Evil Toddler',
 array['evil toddler','사악한 아기','음흉한 미소 아기'],
 '음흉하게 웃는 아기 사진. 짓궂은 장난이나 못된 계획을 꾸밀 때의 심보를 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Megamind Peeking',
 array['megamind peeking','no bitches','메가마인드 훔쳐보기'],
 '메가마인드가 화면 밖을 빼꼼 훔쳐보는 장면. "~가 없다고?" 식으로 상대를 놀릴 때 쓰는 템플릿.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Third World Success Kid',
 array['third world success','성공 아이 아프리카','기대 어긋난 성공'],
 '제3세계 배경의 아이 사진에 반어적 성공/실패 문구를 붙이는 어드바이스 애니멀 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Y U No',
 array['y u no guy','와이유노','why you no'],
 '손을 뻗은 얼굴 그림에 "왜 X 안 해?!"라 항의하는 초기 랄로 밈. 답답한 상황의 원망을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Black Girl Wat',
 array['black girl wat','뭐라고 소녀','황당한 아이'],
 '어린 여자아이가 어리둥절하게 "뭐?" 하는 표정. 이해 안 되는 말을 들었을 때의 반응을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Grandma Finds The Internet',
 array['grandma internet','인터넷 발견 할머니','컴퓨터 할머니'],
 '구형 컴퓨터 앞에 앉은 할머니 사진. 인터넷 문화를 뒤늦게 접한 세대의 순진한 반응을 흉내 낼 때 씀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Finding Neverland',
 array['finding neverland','우는 조니 뎁','억지 눈물'],
 '영화 촬영 중 조니 뎁이 억지로 우는 장면. 슬픈 척하지만 실은 우스운 상황을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Spider-Man Pointing',
 array['spiderman pointing','스파이더맨 손가락질','서로 지목'],
 '두 스파이더맨이 서로를 가리키는 애니메이션 장면. 똑같은 둘이 서로 탓하거나 지목하는 상황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Where Monkey',
 array['where monkey','원숭이 어디','confused monkey'],
 '무언가를 찾는 원숭이 짤에 "where X" 식으로 뭔가가 사라졌음을 표현하는 미니멀 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('I Should Buy A Boat Cat',
 array['i should buy a boat','보트 살까 고양이','신문 보는 고양이'],
 '식탁에서 신문을 보는 고양이 사진에 "보트나 살까" 같은 즉흥적 결심을 붙이는 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Jack Sparrow Being Chased',
 array['jack sparrow chased','쫓기는 잭 스패로우','도망 해적'],
 '캐리비안의 해적 잭 스패로우가 원주민 무리에게 쫓기며 달아나는 장면. 문제를 저지르고 도망칠 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Sparta Leonidas',
 array['this is sparta','스파르타','레오니다스 발차기'],
 '영화 300에서 레오니다스가 "This is Sparta!" 외치며 발로 차는 장면. 무언가를 격하게 거부·강조할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('See Nobody Cares',
 array['see nobody cares','아무도 신경 안 써','텅 빈 극장'],
 '텅 빈 극장을 가리키며 "봐, 아무도 신경 안 써"라 말하는 장면. 관심 못 받는 이야기를 비꼴 때 씀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Maury Lie Detector',
 array['maury lie detector','거짓말 탐지기','that was a lie'],
 '토크쇼 진행자 모리가 "그건 거짓말이었습니다"라 판정하는 장면. 뻔한 거짓을 폭로할 때 쓰는 템플릿.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Pawn Stars Best I Can Do',
 array['pawn stars','best i can do','전당포 릭'],
 '전당포 프로그램에서 릭이 "내가 해줄 수 있는 최선은 이거야"라며 헐값을 부르는 장면. 인색한 제안을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Three-Headed Dragon',
 array['three headed dragon','머리 셋 용','같은 편 3인'],
 '머리 셋 달린 용의 각 머리에 라벨을 붙여, 결국 다 한통속임을 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Laughing Men In Suits',
 array['laughing men in suits','비웃는 정장 남자들','hahaha no'],
 '정장 차림 남자들이 크게 웃는 스톡 사진. 어이없는 요청에 코웃음 칠 때 쓰는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Yo Dawg',
 array['yo dawg','xzibit','pimp my ride'],
 '래퍼 Xzibit가 "야, 네가 X를 좋아한다길래 X 안에 X를 넣었어"라 말하는 재귀 구조 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Too Damn High',
 array['too damn high','jimmy mcmillan','임대료 너무 높아'],
 '정치인 지미 맥밀런이 "X가 너무 높아"라 외치는 장면. 무언가가 지나치게 과하다고 강조할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('10 Guy',
 array['10 guy','stoner stanley','취한 남자'],
 '몽롱한 표정의 남자 사진에 두서없고 엉뚱한 말을 적는 밈. 정신 나간 발상을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Mother Ignoring Kid Drowning In A Pool',
 array['mother ignoring kid','물에 빠진 아이','진짜 관심사'],
 '엄마가 물에 빠진 아이는 무시하고 다른 걸 챙기는 사진. 정작 중요한 건 방치하고 딴 데 몰두하는 상황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Flex Tape',
 array['flex tape','phil swift','방수 테이프'],
 '필 스위프트가 플렉스 테이프로 무엇이든 뚝딱 때우는 광고 장면. 억지로 문제를 덮어버릴 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Dr Evil Laser',
 array['dr evil','laser','오스틴 파워스 손가락'],
 '오스틴 파워스의 닥터 이블이 손가락을 입가에 대고 "레이저"라 비꼬듯 말하는 장면. 대단찮은 걸 과장할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Imagination Spongebob',
 array['imagination spongebob','상상 무지개','스폰지밥 손 무지개'],
 '스폰지밥이 두 손으로 무지개를 그리며 "상상~"이라 말하는 장면. 현실도피성 상상을 비꼴 때 씀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Disappointed Black Guy',
 array['disappointed black guy','실망한 남자','고개 돌리는 남자'],
 '기대에 찼다가 실망해 고개를 돌리는 남자 사진. 기대가 어긋났을 때의 낙담을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Am I The Only One Around Here',
 array['am i the only one','big lebowski','월터 총'],
 '빅 리보스키의 월터가 총을 겨누며 "여기서 나만 X한 거야?"라 흥분하는 장면. 혼자만 정상인 듯한 답답함을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Types Of Headaches',
 array['types of headaches','두통 종류','의학 도표 패러디'],
 '두통 종류를 나열한 의학 도표를 패러디해 마지막에 엉뚱한 원인을 끼워 넣는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('You Guys Are Getting Paid',
 array['you guys are getting paid','월급 받아?','놀란 광부'],
 '"너희 돈 받고 일하는 거였어?"라며 놀라는 반응. 나만 손해 보고 있었음을 깨달을 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Put It Somewhere Else Patrick',
 array['put it somewhere else patrick','다른 데 둬 패트릭','막무가내 패트릭'],
 '패트릭이 해법을 제시받고도 엉뚱하게 우기는 장면. 말이 안 통하는 고집을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Face You Make Robert Downey Jr',
 array['rdj face','다우니 표정','셜록 뜨악'],
 '로버트 다우니 주니어가 뜨악한 표정으로 옆을 보는 장면. 어이없는 말을 들었을 때의 얼굴을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('A Train Hitting A School Bus',
 array['train hitting bus','기차 스쿨버스','압도적 충돌'],
 '기차가 스쿨버스를 들이받는 사진에 두 대상을 라벨링해 압도적인 우위를 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Squidward Window',
 array['squidward window','창밖 징징이','외로운 스퀴드워드'],
 '징징이가 창밖으로 홀로 내다보는 장면. 소외감이나 쓸쓸함을 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Bernie I Am Once Again Asking',
 array['bernie asking','버니 다시 부탁','once again asking'],
 '버니 샌더스가 "다시 한번 여러분의 지지를 부탁드립니다"라 호소하는 모금 영상 캡처 템플릿.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'celebrity', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Be Like Bill',
 array['be like bill','빌처럼','막대기 빌'],
 '막대기 인간 빌이 현명하게 처신한다며 "빌처럼 되세요"라 훈수 두는 밈. 잔소리성 조언을 비꼴 때도 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Bad Pun Dog',
 array['bad pun dog','말장난 개','아재개그 개'],
 '능글맞게 웃는 개 사진에 유치한 말장난(pun)을 붙이는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Mugatu So Hot Right Now',
 array['mugatu so hot','주랜더','지금 대세'],
 '영화 주랜더의 무가투가 "X가 지금 완전 대세지"라 말하는 장면. 유행을 비꼴 때 쓰는 템플릿.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Grant Gustin Over Grave',
 array['grant gustin grave','무덤 앞 남자','묘비 합성'],
 '무덤 앞에 선 그랜트 거스틴 사진에 묘비 문구를 바꿔 넣어 무언가의 죽음을 선언하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Confused Gandalf',
 array['confused gandalf','혼란 간달프','frodo 어디'],
 '간달프가 혼란스러운 표정을 짓는 반지의 제왕 장면. 어리둥절한 상황을 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('What Do We Want',
 array['what do we want','우리가 원하는 것','시위 구호'],
 '시위 구호 "우리가 원하는 건? / 언제? " 형식을 비틀어 모순되거나 우스운 요구를 만드는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Say That Again I Dare You',
 array['say that again','사무엘 잭슨','다시 말해봐'],
 '펄프 픽션의 새뮤얼 잭슨이 "한 번만 더 말해봐"라며 위협하는 장면. 도발에 발끈하는 상황을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Simba Shadowy Place',
 array['simba shadowy place','라이온킹 그림자','가지 마'],
 '라이온킹에서 무파사가 "저 그림자 진 곳엔 절대 가지 마라"라 이르는 장면. 금지된 영역을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Conspiracy Keanu',
 array['conspiracy keanu','음모론 키아누','what if'],
 '키아누 리브스가 대마 든 표정으로 "만약에 말이야…" 하며 음모론을 던지는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Pepperidge Farm Remembers',
 array['pepperidge farm remembers','기억한다','패밀리가이 옛날'],
 '패밀리 가이 밈으로 "페퍼리지 팜은 기억합니다"라며 옛것을 추억하는 향수형 템플릿.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Buddy Christ',
 array['buddy christ','친근한 예수','엄지 예수'],
 '엄지를 치켜든 친근한 예수상. 무언가를 유쾌하게 승인·축복할 때 쓰는 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'character', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Good Fellas Hilarious',
 array['goodfellas funny how','조 페시','웃기다고?'],
 '영화 좋은 친구들에서 조 페시가 "내가 웃겨? 어떻게 웃긴데?"라 몰아붙이는 장면.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Squidward Dab',
 array['squidward chair','앉은 징징이','의자 징징이'],
 '징징이가 의자에 무심히 앉아 있는 장면. 시큰둥하거나 지친 반응을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('I''m The Captain Now',
 array['im the captain now','캡틴 필립스','해적 선장'],
 '영화 캡틴 필립스의 소말리아 해적이 "이제 내가 선장이야"라 선언하는 장면. 주도권을 뺏어올 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('And Everybody Loses Their Minds',
 array['everybody loses their minds','다크나이트 조커','다들 난리나지'],
 '다크나이트 조커가 "그러면 다들 이성을 잃지"라 설명하는 장면. 특정 사건에 사람들이 과잉 반응함을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Marvel Civil War',
 array['marvel civil war','시빌워','편 가르기'],
 '마블 시빌워 대립 구도를 빌려 양측에 라벨을 붙여 갈등을 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Charlie Conspiracy',
 array['charlie conspiracy','pepe silvia','실뭉치 보드'],
 '잇츠 올웨이즈 서니의 찰리가 실과 메모로 뒤덮인 보드 앞에서 열변을 토하는 장면. 과열된 음모론적 분석을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Gus Fring We Are Not The Same',
 array['gus fring','we are not the same','격이 다르다'],
 '브레이킹 배드의 구스 프링 이미지로 "나와 너는 격이 다르다"라며 우월함을 과시하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Friendship Ended',
 array['friendship ended','우정은 끝났다','new best friend'],
 '"이제 X와의 우정은 끝났다. 오늘부터 Y가 내 절친이다"라는 파키스탄발 인물 사진 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Afraid To Ask Andy',
 array['afraid to ask andy','물어보기 무서운 앤디','the office andy'],
 '더 오피스 앤디 이미지로 "이제 와서 물어보기 부끄러운" 기본 상식을 고백하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Ain''t Nobody Got Time For That',
 array['aint nobody got time','sweet brown','시간 없어'],
 '인터뷰이 스위트 브라운의 "그럴 시간 없어"라는 말이 노래로 리믹스된 고전 밈.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Bell Curve',
 array['bell curve','iq bell curve','종형 곡선'],
 '종형 곡선 양 끝의 저지능·고지능이 같은 결론에 도달하고 중간만 헤매는 구도의 밈. 단순함이 정답일 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Domino Effect',
 array['domino effect','도미노','점점 커지는 결과'],
 '작은 도미노가 점점 큰 도미노를 쓰러뜨리는 그림. 사소한 시작이 거대한 결과로 이어짐을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Two Guys On A Bus',
 array['two guys on a bus','버스 두 남자','긍정 vs 부정'],
 '버스 한쪽엔 밝은 풍경을, 반대쪽엔 벽을 보는 두 남자 그림. 같은 상황을 대하는 상반된 태도를 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Two Paths',
 array['two paths','갈림길','기괴한 지름길'],
 '평범한 길과 기괴하지만 솔깃한 길이 갈리는 그림. 정상 대신 이상한 선택으로 새는 상황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Car Salesman Slaps Roof',
 array['car salesman slaps roof','차 지붕 두드리기','이 차로 말할 것 같으면'],
 '중고차 판매원이 차 지붕을 탁 치며 "이 녀석으로 말할 것 같으면" 하고 과장 광고하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Scooby Doo Mask Reveal',
 array['scooby doo mask','가면 벗기기','정체 폭로'],
 '스쿠비 두에서 악당의 가면을 벗겨 정체를 드러내는 장면. 무언가의 진짜 정체를 폭로할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Soyboy Vs Yes Chad',
 array['soyboy vs yes chad','소이 vs 예스차드','nordic gamer'],
 '징징대는 소이잭과 당당한 예스 차드를 대비시키는 워잭 코믹 포맷. 주관 없는 다수 vs 소신파를 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'character', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Scumbag Steve',
 array['scumbag steve','양아치 스티브','모자 남자'],
 '옆으로 삐딱하게 모자 쓴 남자 사진. 뻔뻔하고 이기적인 민폐 행동을 표현하는 어드바이스 애니멀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Star Wars No',
 array['star wars no','다스 베이더 노','noooo'],
 '다스 베이더가 "안 돼애애!" 하고 절규하는 장면. 극적인 거부·절망을 과장할 때 쓰는 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Mr McMahon Reaction',
 array['mcmahon reaction','점점 흥분하는 맥마흔','wwe 회장'],
 'WWE 빈스 맥마흔이 점점 격하게 흥분하는 4단 반응. 무언가에 점점 열광하는 정도를 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Empty Stonks',
 array['empty stonks','빈 스톤크스','손해 밈맨'],
 '스톤크스 밈맨이 텅 빈 그래프 앞에 선 변형. 손해나 공허함을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Absolute Cinema',
 array['absolute cinema','완벽한 영화','마틴 스코세이지'],
 '스코세이지가 두 팔을 든 흑백 사진에 "이것이 진정한 영화"라 감탄하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Jackie Chan WTF',
 array['jackie chan wtf','성룡 뭐야','황당 성룡'],
 '성룡이 양팔을 벌리며 "대체 뭐야?" 하는 황당한 표정. 어이없는 상황을 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Grim Reaper Knocking',
 array['grim reaper knocking','저승사자 노크','점점 다가오는 죽음'],
 '저승사자가 여러 문을 차례로 두드리며 점점 다가오는 4컷. 피할 수 없이 닥치는 결말을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Will Smith Slapping Chris Rock',
 array['will smith slap','오스카 따귀','크리스 록 따귀'],
 '2022 오스카에서 윌 스미스가 크리스 록의 뺨을 때린 순간이 밈화. 참지 못하고 응징하는 상황을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Two Guys On Computer Desk',
 array['spiderman computer desk','책상 위 스파이더맨','웅크린 남자'],
 '책상 위에 웅크린 스파이더맨(피터 파커) 사진. 궁지에 몰려 초조해하는 상황을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Overly Attached Girlfriend',
 array['overly attached girlfriend','집착 여친','OAG'],
 '카메라를 뚫어져라 응시하는 여자 사진. 과도하게 집착하는 연인을 희화화하는 고전 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Here''s Johnny',
 array['heres johnny','샤이닝 잭','문 부수기'],
 '영화 샤이닝에서 잭 니콜슨이 부순 문 사이로 "Here''s Johnny!"라 외치는 장면.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('You Know I''m Something Of A Scientist Myself',
 array['something of a scientist','고블린 윌럼 데포','나도 과학자야'],
 '스파이더맨의 그린 고블린(윌럼 데포)이 "나도 나름 과학자거든"이라 말하는 장면. 어설픈 전문가 흉내를 비꼴 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Say The Line Bart',
 array['say the line bart','대사 좀 해 바트','심슨 뻔한 대사'],
 '심슨 가족에서 관객이 바트에게 "그 대사 좀 해!"라 조르는 장면. 뻔한 유행어를 억지로 반복시킬 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Obama Medal',
 array['obama medal','오바마 자기 훈장','self award'],
 '오바마가 자기 자신에게 훈장을 걸어주는 합성 밈. 스스로를 치켜세우는 상황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('The Office Congratulations',
 array['office congratulations','마이클 축하','kevin 축하'],
 '더 오피스에서 축하하는 장면을 활용한 반어적 축하 템플릿.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Sure Grandma Let''s Get You To Bed',
 array['sure grandma','할머니 주무세요','무시하는 대꾸'],
 '심슨의 노망난 할머니를 침대로 데려가는 장면. 헛소리하는 상대를 부드럽게 무시할 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Lisa Simpson Presentation',
 array['lisa presentation','리사 발표','프로젝터 리사'],
 '리사 심슨이 프로젝터로 발표하는 장면. 진지하게 주장을 펼치는 템플릿으로 자주 쓰임.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Never Ask A Woman Her Age',
 array['never ask','세 가지 금기','don''t ask'],
 '"여자에게 나이를, 남자에게 연봉을, X에게 Y를 묻지 마라" 형식의 3연 금기 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Kevin Hart Reaction',
 array['kevin hart','케빈 하트 반응','눈 크게'],
 '케빈 하트의 다양한 놀란·황당 표정을 활용한 반응짤 세트.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Presidential Alert',
 array['presidential alert','긴급재난문자','비상 경보'],
 '휴대폰 긴급재난문자 화면을 흉내 내 엉뚱한 경보 문구를 넣는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Leonardo DiCaprio Wolf Of Wall Street',
 array['wolf of wall street','월가의 늑대','가슴 치는 디카프리오'],
 '월가의 늑대에서 디카프리오가 가슴을 치며 함성하는 장면. 확신에 찬 자신감을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Peter Parker Cry',
 array['peter parker cry','우는 피터 파커','토비 눈물'],
 '토비 맥과이어의 피터 파커가 눈물 흘리는 장면. 슬프거나 억울한 감정을 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Liam Neeson Particular Set Of Skills',
 array['taken','리암 니슨 전화','특별한 기술'],
 '영화 테이큰에서 리암 니슨이 전화로 "나에겐 특별한 능력이 있다"라 협박하는 장면.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Peter Griffin News',
 array['peter griffin news','피터 그리핀 뉴스','앵커 피터'],
 '패밀리 가이의 피터 그리핀이 뉴스 앵커석에 앉은 장면. 짧은 속보 형식으로 개그를 칠 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Kermit Window Reflection',
 array['kermit window','창가 케르밋','자기 반성 케르밋'],
 '케르밋이 어두운 창가에서 자기 성찰하듯 앉은 장면. 후회나 내적 갈등을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Sad Cat Thumbs Up',
 array['sad cat thumbs up','엄지 든 슬픈 고양이','억지 괜찮아'],
 '울먹이는 고양이가 억지로 엄지를 치켜든 합성. 속상하지만 애써 괜찮은 척할 때 쓰는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Elmo Fire',
 array['elmo fire','불타는 엘모','chaos elmo'],
 '불길 앞에서 팔을 벌린 엘모 짤. 혼돈이나 파괴적 만족감을 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Squidward Sleeping',
 array['squidward chores','징징이 심부름','24 hours later'],
 '스폰지밥의 시간 경과 자막("몇 시간 후") 장면을 활용해 지루한 기다림을 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Soyjak',
 array['soyjak','소이잭','excited wojak'],
 '입을 헤 벌리고 흥분한 워잭 변형. 지나치게 열광하거나 순진한 반응을 조롱할 때 쓰는 캐릭터 밈.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Yes Chad',
 array['yes chad','예스 차드','nordic gamer'],
 '금발의 각진 워잭이 반론에 그저 "yes"라 답하는 장면. 다수 의견에도 소신을 굽히지 않는 태도를 표현.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Crying Wojak',
 array['crying wojak','우는 워잭','frustrated wojak'],
 '이를 악물고 눈물 흘리는 워잭. 억울함·분노·서러움을 표현하며, 가면을 쓴 변형(속내 감추기)도 유명.',
 array['#고전','#감정','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Doomer',
 array['doomer','두머','후드 담배 워잭'],
 '후드를 뒤집어쓰고 담배 문 워잭. 미래에 대한 허무·비관에 빠진 청년상을 대변하는 캐릭터.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Chad',
 array['chad','차드','virgin vs chad'],
 '자신감 넘치는 이상적 남성상 캐릭터. "Virgin vs Chad" 비교 포맷에서 우월한 쪽으로 등장.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Virgin vs Chad',
 array['virgin vs chad','버진 vs 차드','비교 포맷'],
 '소심한 Virgin과 당당한 Chad를 나란히 비교하는 라벨링 포맷. 두 태도·집단을 대비할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Chudjak',
 array['chudjak','처드잭','분노 워잭'],
 '분노에 찬 워잭 변형 처드잭. 외집단을 조롱하는 용도로 쓰이는 캐릭터.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Crying Soyjak vs Mewing Jaw',
 array['crying soyjak mewing','뮤잉 vs 소이잭','looksmaxxing 밈'],
 '우는 소이잭과 뮤잉 다이어그램을 대비시키는 포맷. 자기관리(뮤잉)를 우월한 쪽으로 두는 밈. 2024.',
 array['#캐릭터','#포맷','#미국','#2024'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Cap / No Cap',
 array['cap','no cap','진짜야 거짓말이야'],
 '"cap"은 거짓말, "no cap"은 진심이라는 뜻의 슬랭. 진위를 강조하거나 헛소리를 지적할 때 씀.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Bussin',
 array['bussin','버신','존맛'],
 '음식이 아주 맛있을 때 "bussin"이라 감탄하는 슬랭. 극찬의 뉘앙스.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Sus',
 array['sus','수상해','among us sus'],
 '"suspicious"의 줄임말로, 누군가 미심쩍을 때 "sus하다"라 말하는 슬랭. 어몽어스에서 대중화.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Based',
 array['based','베이스드','소신 발언'],
 '남 눈치 안 보고 소신을 밀어붙이는 태도를 칭찬하는 슬랭 "based". cringe의 반대 개념.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Cringe',
 array['cringe','크린지','오글거림'],
 '보기 민망하고 오글거리는 것을 뜻하는 슬랭 "cringe". based의 반대편.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Simp',
 array['simp','심프','호구'],
 '이성에게 과하게 헌신하며 굽신대는 사람을 뜻하는 슬랭 "simp".',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Slay',
 array['slay','슬레이','잘했어'],
 '무언가를 멋지게 해냈을 때 "slay"라 칭찬하는 슬랭. 응원·감탄의 뉘앙스.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('It''s Giving',
 array['its giving','느낌 난다','분위기 밈'],
 '"~한 느낌이 난다"를 "it''s giving X"로 표현하는 슬랭. 분위기나 인상을 묘사할 때 씀.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Ate And Left No Crumbs',
 array['ate no crumbs','완벽하게 해냄','부스러기도 안 남김'],
 '완벽하게 해냈다는 뜻의 "ate and left no crumbs" 슬랭. 흠잡을 데 없는 수행을 칭찬.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Mid',
 array['mid','미드','그저 그럼'],
 '특별할 것 없이 평범하거나 별로인 것을 "mid"라 평하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Ratio',
 array['ratio','레이시오','답글이 더 많음'],
 'SNS에서 원글보다 반박 답글이 더 많은 호응을 받는 상황을 "ratio"라 부르는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Touch Grass',
 array['touch grass','잔디 좀 만져','현실로 나가'],
 '온라인에 너무 빠진 사람에게 "밖에 나가 잔디나 만져"라며 현실 복귀를 권하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Ok Boomer',
 array['ok boomer','오케이 부머','꼰대 무시'],
 '기성세대의 잔소리에 "네 알겠어요, 부머"라며 가볍게 일축하는 세대 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Living Rent Free',
 array['rent free','머릿속 월세','계속 떠오름'],
 '무언가가 계속 머릿속을 맴돌 때 "내 머릿속에 월세도 안 내고 산다"라 표현하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Vibe Check',
 array['vibe check','분위기 점검','바이브 체크'],
 '누군가의 기분·태도를 불시에 점검한다는 "vibe check" 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Menace To Society',
 array['menace to society','사회악','말썽꾼'],
 '짓궂은 장난을 저지른 대상을 "사회의 위협"이라 과장해 부르는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Cheugy',
 array['cheugy','츄기','한물간 감성'],
 '유행 지났거나 촌스러운 것을 뜻하는 슬랭 "cheugy". 주로 밀레니얼 감성을 놀릴 때 씀.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Girlboss',
 array['girlboss','걸보스','당찬 여성'],
 '야망 있는 커리어 여성상을 뜻하다 반어적으로도 쓰이게 된 "girlboss" 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Gaslight Gatekeep Girlboss',
 array['gaslight gatekeep girlboss','3G','걸보스 3종'],
 '"gaslight, gatekeep, girlboss"를 나란히 붙여 유행어를 반어적으로 조합한 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Caught In 4K',
 array['caught in 4k','4K로 딱 걸림','증거 포착'],
 '빼도 박도 못하게 증거가 선명히 잡혔을 때 "4K로 걸렸다"라 하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Let Him Cook',
 array['let him cook','요리하게 둬','지켜봐'],
 '누군가 몰두해 뭔가를 만들 때 "방해 말고 요리하게 둬"라며 지켜보라는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('The Ick',
 array['the ick','정 떨어짐','ick'],
 '상대에게 갑자기 정나미가 뚝 떨어지는 순간을 "the ick"이라 부르는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('NPC',
 array['npc','엔피씨','기계적 반응'],
 '게임 배경 캐릭터처럼 정해진 말만 반복하는 사람을 "NPC"라 조롱하는 밈. 틱톡 NPC 라이브 스트림으로 재유행.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Canadian Kid Cat / IShowSpeed',
 array['ishowspeed','스피드','스트리머 리액션'],
 '스트리머 아이쇼스피드의 격한 리액션들이 다양한 반응짤로 밈화. 과장된 흥분·경악을 표현.',
 array['#고전','#크리에이터','#미국','#스테디'],
 'new', 'celebrity', 'https://knowyourmeme.com/', null),

('Kai Cenat',
 array['kai cenat','카이 세나트','rizz 유행어'],
 '스트리머 카이 세나트가 대중화한 "rizz" 등 유행어와 리액션들이 밈으로 확산.',
 array['#고전','#크리에이터','#미국','#스테디'],
 'new', 'celebrity', 'https://knowyourmeme.com/', null),

('Duolingo Owl',
 array['duolingo owl','듀오링고 부엉이','협박 부엉이'],
 '학습을 안 하면 쫓아온다는 듀오링고 부엉이 마스코트가 협박성 밈으로 확산.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Girl Math',
 array['girl math','걸 매스','합리화 셈법'],
 '현금으로 사면 공짜, 환불받으면 번 셈 등 소비를 유쾌하게 합리화하는 "걸 매스" 밈. 2023~2024.',
 array['#유행어','#틱톡','#미국','#2024'],
 'new', 'catchphrase', 'https://www.nbcnews.com/pop-culture/best-memes-moments-2024-brat-demure-hawk-tuah-rcna181956', null),

('Roman Empire',
 array['roman empire','로마 제국','얼마나 자주 생각해'],
 '"남자들이 얼마나 자주 로마 제국을 생각하는가"라는 질문이 밈이 되어 각자의 "로마 제국"을 고백. 2023~2024.',
 array['#유행어','#틱톡','#미국','#2024'],
 'new', 'catchphrase', 'https://www.nbcnews.com/pop-culture/best-memes-moments-2024-brat-demure-hawk-tuah-rcna181956', null),

('Underconsumption Core',
 array['underconsumption core','저소비 코어','안 사기'],
 '과소비를 거부하고 이미 가진 것을 아껴 쓰자는 틱톡 트렌드. 2024.',
 array['#라이프스타일','#틱톡','#미국','#2024'],
 'new', 'format', 'https://www.fox9.com/news/best-memes-2024', null),

('Moo Deng Pygmy Hippo',
 array['moo deng','무뎅','피그미 하마'],
 '태국 동물원의 아기 피그미하마 무뎅. 통통 튀는 표정으로 세계적 인기를 끈 2024 동물 밈.',
 array['#동물','#틱톡','#미국','#2024'],
 'new', 'animal', 'https://www.fox9.com/news/best-memes-2024', null),

('Pesto Penguin',
 array['pesto penguin','페스토 펭귄','거대 아기 펭귄'],
 '부모보다 커진 아기 킹펭귄 페스토가 2024년 귀여운 동물 밈으로 확산.',
 array['#동물','#틱톡','#미국','#2024'],
 'new', 'animal', 'https://www.fox9.com/news/best-memes-2024', null),

('Bombombini Gusini',
 array['bombombini gusini','봄봄비니 구시니','거위 폭격기'],
 '거위와 폭격기를 섞은 AI 캐릭터. 봄바르디로 크로코딜로와 엮이는 이탈리안 브레인롯 파생. 2025.',
 array['#브레인롯','#AI','#미국','#2025'],
 'new', 'brainrot', 'https://en.wikipedia.org/wiki/Italian_brainrot', null),

('Trippi Troppi',
 array['trippi troppi','트리피 트로피','브레인롯 캐릭터'],
 '이탈리안 브레인롯 계열의 초현실 AI 캐릭터. 리듬감 있는 이름과 나레이션이 특징. 2025.',
 array['#브레인롯','#AI','#미국','#2025'],
 'new', 'brainrot', 'https://en.wikipedia.org/wiki/Italian_brainrot', null),

('Boneca Ambalabu',
 array['boneca ambalabu','보네카 암발라부','타이어 개구리'],
 '타이어와 개구리를 합친 초현실 AI 캐릭터. 인도네시아발로 브레인롯 세계관에 편입. 2025.',
 array['#브레인롯','#AI','#미국','#2025'],
 'new', 'brainrot', 'https://en.wikipedia.org/wiki/Italian_brainrot', null),

('Tralalero Shark Nike',
 array['tralalero','나이키 상어','세 다리 상어'],
 '파란 나이키를 신은 세 다리 상어 AI 캐릭터. 이탈리안 브레인롯의 초기 대표작. 2025.',
 array['#브레인롯','#AI','#미국','#2025'],
 'new', 'brainrot', 'https://en.wikipedia.org/wiki/Italian_brainrot', null),

('Steal A Brainrot',
 array['steal a brainrot','로블록스 브레인롯','brainrot 게임'],
 '브레인롯 캐릭터를 훔쳐 모으는 로블록스 게임이 수백만 아동에게 폭발적 인기를 끈 현상. 2025.',
 array['#게임','#브레인롯','#미국','#2025'],
 'new', 'video', 'https://en.wikipedia.org/wiki/Italian_brainrot', null),

('Just Put The Fries In The Bag',
 array['fries in the bag','감자튀김 봉지에','변명 그만'],
 '변명하는 상대에게 "됐고 감자튀김이나 봉지에 넣어"라며 쏘아붙이는 유행어. 2024~2025.',
 array['#유행어','#틱톡','#미국','#2025'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Costco Guys',
 array['costco guys','코스트코 가이즈','we bring the boom'],
 '부자(父子) 인플루언서 코스트코 가이즈의 "we bring the boom" 구호와 점수 매기기가 밈화. 2024~2025.',
 array['#크리에이터','#틱톡','#미국','#2025'],
 'new', 'celebrity', 'https://knowyourmeme.com/', null),

('Baby Gronk',
 array['baby gronk','베이비 그롱크','livvy rizzed'],
 '유소년 미식축구 유망주 베이비 그롱크와 관련 "rizz" 밈이 2023~2024 확산.',
 array['#유행어','#틱톡','#미국','#2025'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Sticking Out Your Gyat',
 array['gyat rizzler','sticking out your gyat','gen alpha 랩'],
 'Gen Alpha 슬랭(gyat, rizz, Ohio, skibidi 등)을 잔뜩 엮은 "sticking out your gyat" 랩이 밈화. 2023~2024.',
 array['#유행어','#GenAlpha','#미국','#2025'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Confession Bear',
 array['confession bear','고백 곰','비밀 털어놓기'],
 '곰이 마이크에 대고 속삭이는 사진에 남몰래 하는 고백을 적는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Uncle Sam',
 array['uncle sam','엉클 샘','i want you'],
 '"I Want You"로 유명한 엉클 샘 포스터를 패러디해 무언가를 강하게 요구하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Back In My Day',
 array['back in my day','라떼는','옛날 할아버지'],
 '노인이 "내 때는 말이야"라며 과거를 회상하는 템플릿. 세대 차이를 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Bugs Bunny Communist',
 array['bugs bunny communist','벅스 버니 공산주의','our meme'],
 '벅스 버니가 "우리 모두의 것"이라 말하는 장면. 소유의 경계가 무의미할 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Shut Up And Take My Money',
 array['take my money','fry 돈','futurama 프라이'],
 '퓨처라마 프라이가 지폐를 들이밀며 "닥치고 내 돈이나 가져가"라 외치는 장면. 사고 싶어 안달난 상황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Soldier Protecting Sleeping Child',
 array['soldier protecting child','자는 아이 지키는 군인','수호 라벨'],
 '군인이 자는 아이를 지키는 그림에 라벨을 붙여 무언가가 다른 것을 보호함을 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('0 Days Without',
 array['0 days without','무사고 며칠','심슨 카운터'],
 '심슨의 발전소 무사고 일수 게시판("X 없이 0일")을 패러디해 반복되는 사고를 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('AJ Styles And Undertaker',
 array['aj styles undertaker','when x sees y','등장 밈'],
 'WWE AJ 스타일스가 언더테이커를 보고 굳는 장면. 예상 못한 상대를 마주쳤을 때의 당황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('What Gives People Feelings Of Power',
 array['feelings of power','권력의 근원','도표 밈'],
 '"무엇이 사람에게 권력감을 주는가" 도표를 패러디해 엉뚱한 답을 끼워 넣는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Spider-Man Triple Pointing',
 array['spiderman triple','세 스파이더맨 지목','삼중 지목'],
 '세 명의 스파이더맨이 서로를 가리키는 확장판. 똑같은 셋이 서로 탓하는 상황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Scared Cat',
 array['scared cat','겁먹은 고양이','놀란 고양이 눈'],
 '눈을 크게 뜨고 겁에 질린 고양이 사진. 충격이나 공포를 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Awkward Seal',
 array['awkward moment seal','어색한 물개','socially awkward'],
 '무늬가 어색해 보이는 물개 사진. 사회적으로 민망한 순간을 표현하는 어드바이스 애니멀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Surprised Koala',
 array['surprised koala','놀란 코알라','입 벌린 코알라'],
 '입을 벌리고 놀란 코알라 사진. 충격적인 소식에 대한 반응을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Spongebob Burning Paper',
 array['spongebob burning paper','불타는 종이','증거 인멸'],
 '스폰지밥이 종이를 태우는 장면. 무언가를 없애버리거나 무시할 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Good Guy Greg',
 array['good guy greg','좋은 녀석 그렉','착한 담배남'],
 '담배 문 남자 사진에 사려 깊고 착한 행동을 적는 밈. Scumbag Steve의 반대격.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Scumbag Brain',
 array['scumbag brain','양아치 뇌','말 안 듣는 뇌'],
 '모자 쓴 뇌 그림에 제멋대로 구는 자기 뇌를 탓하는 밈. 잠 안 오거나 딴생각날 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Overly Manly Man',
 array['overly manly man','과하게 남자다운','마초 남자'],
 '콧수염의 옛날 남성 사진에 극단적으로 마초적인 허세를 적는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Ermahgerd Girl',
 array['ermahgerd','책 든 소녀','교정기 소녀'],
 '교정기 낀 소녀가 흥분해 "ermahgerd"라 외치는 사진. 엉터리 발음으로 열광을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Insanity Wolf',
 array['insanity wolf','광기 늑대','극단 늑대'],
 '으르렁대는 늑대 사진에 극단적이고 과격한 해결책을 적는 어드바이스 애니멀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Courage Wolf',
 array['courage wolf','용기 늑대','동기부여 늑대'],
 '포효하는 늑대에 강한 동기부여 문구를 적는 밈. Insanity Wolf의 순한 버전.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Actual Advice Mallard',
 array['advice mallard','조언 오리','꿀팁 오리'],
 '청둥오리 사진에 실제로 유용한 생활 팁을 적는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Sudden Clarity Clarence',
 array['sudden clarity clarence','갑작스런 깨달음','클라렌스'],
 '파티에서 문득 깨달은 듯한 남자 사진. 뜬금없는 통찰이 떠오른 순간을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Socially Awkward Penguin',
 array['socially awkward penguin','소심한 펭귄','어색한 펭귄'],
 '파란 배경의 펭귄 사진에 사회적으로 서툰 순간을 적는 어드바이스 애니멀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Socially Awesome Penguin',
 array['socially awesome penguin','인싸 펭귄','빨간 펭귄'],
 '빨간 배경 펭귄에 사교적으로 능숙한 순간을 적는 밈. 소심 펭귄의 반대.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Business Cat',
 array['business cat','넥타이 고양이','사장 고양이'],
 '넥타이 맨 고양이 사진에 고양이스러운 회사 지시를 적는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Grumpy Cat No',
 array['grumpy cat no','심술 고양이 노','tard'],
 '심술 고양이가 "No."라 딱 잘라 거절하는 밈. 시니컬한 거부를 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Nyan Cat Rainbow',
 array['nyan cat','냥캣','무지개 고양이'],
 '팝타르트 몸통의 픽셀 고양이가 무지개를 뿜으며 나는 GIF. 초기 인터넷 GIF 밈.',
 array['#고전','#GIF','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Pop Cat',
 array['popcat','팝캣','입 벌리는 고양이'],
 '입을 뻥긋 벌렸다 닫는 고양이 "팝캣". 클릭 게임으로도 유행한 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Cat Vibing',
 array['vibing cat','리듬 타는 고양이','오이아 오이'],
 '고개를 까딱이며 리듬 타는 고양이 GIF. 각종 음악에 맞춰 무한 리믹스된 밈.',
 array['#고전','#GIF','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', 'https://media1.tenor.com/m/wcwv_21ZuswAAAAd/vibing-cat.gif'),

('Bongo Cat',
 array['bongo cat','봉고 고양이','악기 고양이'],
 '앞발로 무엇이든 두드리는 고양이 "봉고 캣". 다양한 악기·상황에 합성됨.',
 array['#고전','#GIF','#미국','#스테디'],
 'new', 'animal', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Sad Frog Feels Bad Man',
 array['feels bad man','슬픈 개구리','sad pepe'],
 '슬픈 표정의 페페(Sad Frog)가 "feels bad man"이라 말하는 원형 밈.',
 array['#고전','#감정','#미국','#스테디'],
 'new', 'character', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Smug Frog',
 array['smug frog','거만한 페페','비웃는 개구리'],
 '능글맞게 웃는 페페(Smug Frog). 우월감이나 조롱을 표현하는 변형.',
 array['#고전','#감정','#미국','#스테디'],
 'new', 'character', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Angry Pepe',
 array['angry pepe','화난 페페','reeee'],
 '격분한 페페가 "REEEE"라 외치는 변형. 분노를 과장할 때 씀.',
 array['#고전','#감정','#미국','#스테디'],
 'new', 'character', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Apu Apustaja',
 array['apu apustaja','도우미 개구리','help helper'],
 '서툴지만 착한 개구리 캐릭터 아푸. 순수하고 어리숙한 감정을 표현하는 페페 파생.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Poggers',
 array['poggers','포그','pogchamp'],
 '놀람·환호를 뜻하는 이모트 "PogChamp/Poggers". 스트리밍 채팅에서 널리 쓰이는 반응.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Monkas',
 array['monkas','몽카','불안 이모트'],
 '땀 흘리는 페페 이모트 "monkaS". 긴장되거나 조마조마한 순간을 표현하는 트위치 이모트.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('KEKW',
 array['kekw','케크','웃음 이모트'],
 '스페인 남자가 크게 웃는 이모트 "KEKW". 트위치 채팅에서 폭소를 표현.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('OMEGALUL',
 array['omegalul','오메가룰','대폭소'],
 '스트리머 얼굴을 왜곡한 웃음 이모트 "OMEGALUL". 극한의 폭소를 표현.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Sadge',
 array['sadge','새지','슬픔 이모트'],
 '시무룩한 페페 이모트 "Sadge". 아쉬움이나 슬픔을 표현하는 트위치 이모트.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Copium',
 array['copium','코피움','정신승리 약'],
 '받아들이기 힘든 현실을 자기합리화로 버티는 것을 "코피움을 흡입한다"라 표현하는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Hopium',
 array['hopium','호피움','헛된 희망'],
 '근거 없는 희망에 매달리는 것을 "호피움"이라 부르는 코피움 파생 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Malding',
 array['malding','몰딩','빡쳐서 대머리'],
 '"mad + balding"의 합성으로, 화가 나서 머리 빠질 지경임을 뜻하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Down Bad',
 array['down bad','다운 배드','심하게 빠짐'],
 '누군가에게 심하게 반하거나 절박한 상태를 "down bad"라 표현하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Cook',
 array['he''s cooking','요리 중','잘 나가는 중'],
 '누군가 일이 잘 풀리며 성과를 낼 때 "쟤 지금 요리 중이야(cooking)"라 하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Goated',
 array['goated','가트','최고다'],
 '"GOAT(역대 최고)"에서 온 형용사 "goated". 최고라 인정할 때 씀.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('W',
 array['w','더블유','승리'],
 '"Win"을 뜻하는 "W". 잘한 일이나 승리를 축약해 표현하는 슬랭. L의 반대.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Take The L',
 array['take the l','엘 먹다','패배 인정'],
 '"Loss"를 뜻하는 "L". 실패나 패배를 인정할 때 "take the L"이라 함.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Yeet',
 array['yeet','윗','냅다 던지기'],
 '무언가를 힘차게 던지거나 내지를 때 외치는 감탄사 "yeet".',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Big Yikes',
 array['big yikes','빅 야익스','완전 민망'],
 '몹시 민망하거나 아찔한 상황을 "big yikes"라 표현하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Sheesh',
 array['sheesh','쉬이이','감탄'],
 '감탄하거나 대단하다고 추어올릴 때 길게 빼서 외치는 "sheeesh" 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Patrick Bateman Staring',
 array['patrick bateman','아메리칸 사이코','시그마 응시'],
 '아메리칸 사이코의 패트릭 베이트먼이 무표정하게 응시하는 장면. 시그마 밈의 아이콘.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Tom And Jerry Point',
 array['tom jerry point','가리키는 톰 제리','둘이 지목'],
 '톰과 제리가 함께 무언가를 손가락질하는 장면. 공동의 적이나 대상을 가리킬 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('SpongeBob Tired',
 array['spongebob tired','지친 스폰지밥','피곤 밈'],
 '축 늘어진 스폰지밥 장면. 극도로 지치거나 번아웃된 상태를 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Patrick Wallet',
 array['patrick wallet','패트릭 지갑','텅 빈 지갑'],
 '패트릭이 빈 지갑을 보여주는 장면. 돈이 없거나 줄 게 없음을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Handsome Squidward',
 array['handsome squidward','잘생긴 징징이','dramatically handsome'],
 '잠깐 미남으로 변한 징징이 장면. 과장된 자신감이나 미모를 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Caveman Spongebob',
 array['spongegar','원시인 스폰지밥','primitive'],
 '원시인 스폰지밥(Spongegar)이 어리둥절해하는 장면. 혼란스럽거나 뒤처진 느낌을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Mr Krabs Blur',
 array['mr krabs blur','혼란 집게사장','어지러운 크랩스'],
 '집게사장이 흐릿하게 뱅뱅 도는 장면. 정신없고 혼란스러운 상태를 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Patrick Not My Wallet',
 array['not my wallet','이건 내 지갑이 아냐','패트릭 헷갈림'],
 '패트릭이 엉뚱한 논리로 우기는 장면. 말귀를 못 알아듣는 상황을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Is Mayonnaise An Instrument',
 array['mayonnaise instrument','마요네즈 악기','패트릭 질문'],
 '패트릭이 "마요네즈도 악기야?"라 엉뚱하게 묻는 장면. 뜬금없는 질문을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://imgflip.com/memetemplates?sort=top-all-time', null),

('Wojak Pointing',
 array['wojak pointing','가리키는 워잭','soyjak pointing'],
 '여러 소이잭이 흥분해 무언가를 가리키는 장면. 화제나 대상에 과하게 반응함을 표현.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Coomer',
 array['coomer','쿠머','중독 워잭'],
 '무언가에 중독된 워잭 변형 "쿠머". 절제 못 하는 탐닉을 조롱.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Gloomer',
 array['gloomer','글루머','우울 워잭'],
 '두머보다 더 침울한 워잭 변형 "글루머". 깊은 우울을 표현.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Bloomer',
 array['bloomer','블루머','희망 워잭'],
 '미래를 낙관하는 밝은 워잭 변형 "블루머". 두머의 반대.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Consoomer',
 array['consoomer','콘수머','소비 워잭'],
 '굿즈를 쟁여 소비하는 워잭 변형 "콘수머". 과소비를 조롱.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Tradwife Wojak',
 array['tradwife wojak','전통 아내 워잭','doomer tradwife'],
 '전통적 아내상을 그린 여성 워잭. 특정 가치관을 희화화하는 워잭 코믹 캐릭터.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Brainlet',
 array['brainlet','브레인렛','작은 뇌 워잭'],
 '머리가 쪼그라든 워잭 "브레인렛". 어리석은 주장을 하는 허수아비 역할.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Wojak Comics',
 array['wojak comics','워잭 코믹','캐릭터 대화'],
 '여러 워잭 캐릭터가 대화하는 만화 포맷. 온갖 상황을 캐릭터 대비로 풀어냄.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Money Printer Go Brrr',
 array['money printer','brrr','돈 찍어내기'],
 '동요하는 워잭과 태연한 부머 워잭을 대비시키고 "돈 찍는 기계 brrr"이라 적는 경제 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Pink Wojak',
 array['pink wojak','핑크 워잭','극한 절규'],
 '얼굴이 붉게 달아오르고 피눈물 흘리는 워잭 변형. 극도의 고통·절규를 표현.',
 array['#고전','#감정','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('I Know That Feel Bro',
 array['i know that feel','포옹 워잭','공감 워잭'],
 '두 워잭이 서로 껴안으며 "그 기분 알아, 친구"라 위로하는 초기 밈.',
 array['#고전','#감정','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('30-50 Feral Hogs',
 array['feral hogs','멧돼지 30-50마리','트위터 밈'],
 '"우리 마당에 30~50마리 야생 멧돼지가 몰려오면 어쩌냐"는 트윗이 부조리 밈으로 확산. 2019.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('They Did Surgery On A Grape',
 array['surgery on a grape','포도 수술','로봇 수술'],
 '수술 로봇으로 포도 껍질을 봉합한 영상에서 "포도에 수술을 했다"는 문구가 부조리 밈이 됨. 2018.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('How Do You Do Fellow Kids',
 array['fellow kids','30 rock','같은 애들'],
 '30 Rock에서 어른이 청소년인 척 "안녕 얘들아"라 어색하게 다가가는 장면. 억지로 젊은 척할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('This Is Bait',
 array['this is bait','이건 미끼야','낚시 경고'],
 '빨간 화살표로 "이건 미끼(bait)야"라 경고하는 밈. 뻔한 도발에 넘어가지 말라는 뜻.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Task Failed Successfully',
 array['task failed successfully','실패했지만 성공','오류 메시지'],
 '"작업이 성공적으로 실패했습니다"라는 모순된 오류 메시지 밈. 뜻밖의 결과를 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Modern Problems Require Modern Solutions',
 array['modern problems','현대적 해결책','kunta kinte'],
 '영화 대사 "현대적 문제엔 현대적 해결책이 필요하지"를 인용해 기발한(또는 편법적) 해법을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Stonks Guy',
 array['stonks guy','밈맨','meme man'],
 '정장 입은 3D 밈맨(Meme Man)이 각종 STONKS 계열 밈의 주인공으로 등장.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Not Stonks',
 array['not stonks','낫 스톤크스','손해 화살표'],
 '하강 화살표 앞의 밈맨 "NOT STONKS". 손해나 하락을 표현하는 스톤크스 변형.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('HODL',
 array['hodl','호들','존버'],
 '폭락장에서도 코인을 팔지 않고 버티는 것을 뜻하는 오타발 밈 "HODL".',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Diamond Hands',
 array['diamond hands','다이아몬드 핸즈','존버 손'],
 '손실에도 매도하지 않고 끝까지 쥐고 버티는 투자자를 "다이아몬드 핸즈"라 부르는 밈. 2021 게임스톱 사태.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('To The Moon',
 array['to the moon','투 더 문','떡상 기원'],
 '자산 가격이 폭등하길 바라며 "달까지 가자"라 외치는 코인·주식 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Nobody Absolutely Nobody',
 array['nobody absolutely nobody','아무도 안 물었는데','nobody:'],
 '"아무도: / 진짜 아무도 안 물었는데:" 형식으로 뜬금없는 행동을 소개하는 밈 포맷.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Me Explaining To My Mom',
 array['me explaining to mom','엄마한테 설명','charlie 보드'],
 '실뭉치 보드 앞에서 열변하는 사진에 "엄마에게 X를 설명하는 나"를 붙이는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Nobody Gonna Know',
 array['nobody gonna know','아무도 모를걸','they wouldnt'],
 '"아무도 모를 거야 / 어떻게 알겠어"라며 은근슬쩍 넘어가려는 인터뷰 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('It Ain''t Much But It''s Honest Work',
 array['honest work','소박하지만 정직한 노동','농부'],
 '농부가 "많진 않지만 정직한 일이지"라 말하는 장면. 소소한 성취를 뿌듯해할 때 씀.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Corporate Needs You To Find The Differences',
 array['find the differences','the office 차이 찾기','둘은 같은 그림'],
 '"이 둘의 차이를 찾아보세요"라 하자 "둘은 같은 그림인데요"라 답하는 더 오피스 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('E',
 array['e meme','마키마 e','알파벳 E'],
 '마키마 얼굴에 알파벳 "E"만 붙인 부조리 밈. 아무 의미 없음이 곧 유머.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Amogus',
 array['amogus','아모구스','among us 변형'],
 '어몽어스 캐릭터를 뭉갠 저화질 "amogus" 밈. 아무 데나 갖다 붙이는 부조리 유머.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('When The Imposter Is Sus',
 array['imposter is sus','임포스터 sus','among us 노래'],
 '"임포스터가 수상할 때"라는 어몽어스 밈 문구와 드립 사운드. 2020~2021.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Pointing Rick Dalton',
 array['rick dalton pointing','가리키는 릭 달튼','디카프리오 손가락질'],
 '원스 어폰 어 타임 인 할리우드의 디카프리오가 TV를 가리키며 알아보는 장면. "어 저거 나 아는 거!"를 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Everything Everywhere Googly Eyes',
 array['googly eyes','구글리 아이즈','모든 순간의 모든 것'],
 '영화 에브리씽 에브리웨어의 구글리 아이(눈알 스티커) 이미지가 감성적 밈으로 확산. 2022.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Polite Cat',
 array['polite cat','공손한 고양이','웃는 회색 고양이'],
 '입꼬리가 올라가 공손히 웃는 듯한 고양이 사진. 예의 바른 척하거나 흐뭇할 때 씀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Screaming Cat',
 array['screaming cat','소리지르는 고양이','입 벌린 고양이'],
 '입을 크게 벌리고 우는 고양이 사진. 격한 감정이나 항의를 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Huh Cat',
 array['huh cat','뭐라고 고양이','뜨악 고양이'],
 '입을 헤 벌리고 "뭐?" 하는 표정의 고양이. 황당함을 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Woman Pointing At Cat',
 array['woman yelling variant','고양이 짤 변형','smudge 변형'],
 '여자가 소리치는 쪽 라벨을 바꿔 쓰는 Woman Yelling at a Cat 파생 포맷.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('They Ask You How You Are',
 array['how you are','괜찮다고 답하지만','속마음 밈'],
 '"사람들이 안부를 물으면 그냥 괜찮다고 답하지"라며 속내를 감추는 자조적 텍스트 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Sad Hamster',
 array['sad hamster','슬픈 햄스터','hampter'],
 '눈물 그렁그렁한 햄스터 사진. 애처롭거나 실망스러운 상황을 표현하는 반응짤. 2023~2024.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Chipi Chipi Chapa Chapa',
 array['chipi chipi','chapa chapa','고양이 노래'],
 '"chipi chipi chapa chapa" 노래에 맞춰 흔들리는 고양이 영상이 밈화. 2024.',
 array['#영상','#틱톡','#미국','#2024'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Oi Oi Oi Baby',
 array['oi oi oi','baby gronk','드립 사운드'],
 '"oi oi oi" 드립 사운드가 각종 등장 장면의 배경음으로 쓰이는 밈. 2024.',
 array['#사운드','#틱톡','#미국','#2024'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Looking At My Wrist Where''s My Money',
 array['wrist money','시계 보며 돈','time is money'],
 '손목의 시계를 보며 "내 시간이 돈인데"라 재촉하는 반응 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Mob Wife Aesthetic',
 array['mob wife','마피아 아내룩','패션 밈'],
 '화려하고 대담한 "마피아 아내" 스타일을 지향하는 2024 패션 트렌드 밈.',
 array['#라이프스타일','#틱톡','#미국','#2024'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Nonchalant',
 array['nonchalant','논샬란트','무심한 척'],
 '일부러 무심하고 쿨한 척하는 태도를 "nonchalant"라 하는 유행어 밈. 2024~2025.',
 array['#유행어','#틱톡','#미국','#2025'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Let Them Cook Variants',
 array['let them cook','요리하게 둬 변형','지켜보기'],
 '몰두한 이를 방해 말라는 "let them cook"의 다양한 응용 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Skull Emoji',
 array['skull emoji','해골 이모지','웃겨 죽음'],
 '너무 웃겨 "죽었다"는 뜻으로 해골 이모지 💀를 쓰는 표현 밈. 웃음의 상징으로 정착.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Real',
 array['real','리얼','공감'],
 '누군가의 말에 깊이 공감할 때 짧게 "real"이라 답하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Fumbled The Bag',
 array['fumbled the bag','기회 날림','가방 놓침'],
 '좋은 기회를 어이없게 날려버린 상황을 "fumbled the bag"이라 하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Secure The Bag',
 array['secure the bag','한몫 챙기기','가방 확보'],
 '이득이나 기회를 확실히 챙긴다는 뜻의 "secure the bag" 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Glazing',
 array['glazing','글레이징','과한 칭찬'],
 '누군가를 지나치게 띄워주며 아부하는 것을 "glazing"이라 하는 슬랭. 2024.',
 array['#유행어','#미국','#2024','#틱톡'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Crash Out',
 array['crash out','크래시 아웃','이성 잃음'],
 '화가 나거나 무너져서 자제력을 잃는 것을 "crash out"이라 하는 슬랭. 2024~2025.',
 array['#유행어','#틱톡','#미국','#2025'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Yapping',
 array['yapping','야핑','수다 떨기'],
 '쓸데없이 말이 많은 것을 "yapping"이라 하는 슬랭. "yapper"는 수다쟁이.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Delusional Delulu',
 array['delulu','델루루','망상 낙관'],
 '근거 없는 낙관·망상을 귀엽게 이르는 "delulu" 슬랭. "delulu is the solulu"로도 확장.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Serving Looks',
 array['serving looks','비주얼 폭발','패션 뽐내기'],
 '차림새나 외모가 아주 훌륭할 때 "serving looks"라 칭찬하는 슬랭.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Main Character Energy',
 array['main character','주인공 기운','서사의 중심'],
 '스스로를 이야기의 주인공처럼 여기는 태도를 "main character energy"라 하는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Villain Era',
 array['villain era','빌런 시기','내 멋대로 시즌'],
 '남 눈치 안 보고 이기적으로 행동하는 시기를 "villain era"라 선언하는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Ok Then',
 array['ok then','그래 뭐','시큰둥'],
 '떨떠름하거나 시큰둥하게 "그래 뭐"라 반응하는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Bro Thinks He''s',
 array['bro thinks hes','쟤 지가 뭐라고','형 착각'],
 '"쟤 지가 X인 줄 아네"라며 상대의 착각을 비꼬는 슬랭 포맷.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Nah He Tweakin',
 array['nah he tweakin','쟤 이상해','instagram 밈'],
 '인스타그램발 유행어 "nah he tweakin(쟤 맛이 갔네)". 어이없는 언행을 비꼴 때 씀. 2021.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('It''s The For Me',
 array['its the for me','그 부분이 킬포','the X for me'],
 '"내겐 그 X가 포인트야(it''s the X for me)" 형식으로 특정 부분을 콕 집는 유행어.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Understandable Have A Nice Day',
 array['understandable have a nice day','이해합니다 좋은 하루','낚시 반응'],
 '무슨 상황이든 "이해합니다, 좋은 하루 되세요"라 무심히 넘기는 낚시성 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Joe Mama',
 array['joe mama','조 마마','니 엄마 낚시'],
 '"Joe가 누구야?"라 되묻게 해 "Joe mama(니 엄마)"로 낚는 말장난 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Deez Nuts',
 array['deez nuts','디즈 넛츠','낚시 개그'],
 '되묻게 유도한 뒤 "deez nuts"로 받아치는 오래된 말장난 낚시 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Certified Hood Classic',
 array['certified hood classic','공인 클래식','명곡 밈'],
 '옛 명곡·명장면에 "certified hood classic" 자막을 붙여 추어올리는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Emotional Damage',
 array['emotional damage','정신적 데미지','steven he'],
 '코미디언 스티븐 허의 "Emotional damage!" 외침이 상처 입은 순간의 반응 밈으로 확산. 2022.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Bird Box Challenge',
 array['bird box','눈 가리고','챌린지 밈'],
 '영화 버드 박스에서 유래해 눈을 가리고 행동하는 챌린지 밈. 2019.',
 array['#고전','#챌린지','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('In My Feelings Challenge',
 array['in my feelings','키키 챌린지','drake 챌린지'],
 '드레이크의 "In My Feelings"에 맞춰 차에서 내려 춤추는 키키 챌린지. 2018.',
 array['#고전','#챌린지','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Ice Bucket Challenge',
 array['ice bucket challenge','아이스버킷','als 기부'],
 '얼음물을 뒤집어쓰고 다음 사람을 지목하는 ALS 기부 캠페인 챌린지. 2014.',
 array['#고전','#챌린지','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Mannequin Challenge',
 array['mannequin challenge','마네킹 챌린지','정지 동작'],
 '모두가 마네킹처럼 얼어붙은 채 카메라가 훑고 지나가는 챌린지. 2016.',
 array['#고전','#챌린지','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Harlem Shake',
 array['harlem shake','할렘 셰이크','떼춤 밈'],
 '한 명이 춤추다 비트 드롭과 함께 모두가 미친 듯이 춤추는 영상 밈. 2013.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Gangnam Style Reaction',
 array['gangnam style','강남스타일 반응','말춤'],
 '싸이의 강남스타일 말춤이 전 세계에서 패러디되며 유튜브 시대 밈의 상징이 됨. 2012.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Damn Daniel',
 array['damn daniel','댐 다니엘','white vans'],
 '"Damn, Daniel! 흰 반스 신었네"라 놀리는 짧은 영상이 밈으로 폭발. 2016.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Cash Me Ousside',
 array['cash me ousside','howbow dah','dr phil 소녀'],
 '닥터 필에 나온 소녀의 "Cash me ousside, howbow dah"가 유행어가 됨. 2017.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'celebrity', 'https://knowyourmeme.com/', null),

('Charlie Bit My Finger',
 array['charlie bit my finger','찰리가 손가락 물었어','형제 영상'],
 '동생 찰리가 형 손가락을 무는 홈비디오가 유튜브 초기 최고 인기 영상 밈이 됨. 2007.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('David After Dentist',
 array['david after dentist','치과 다녀온 데이비드','마취 아이'],
 '마취에서 덜 깬 아이 데이비드가 "이게 진짜야?"라 묻는 홈비디오 밈. 2009.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Chocolate Rain',
 array['chocolate rain','초콜릿 레인','tay zonday'],
 '테이 존데이의 저음 노래 "Chocolate Rain"이 초기 유튜브 밈으로 확산. 2007.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Numa Numa',
 array['numa numa','누마 누마','dragostea din tei'],
 '게리 브롤스마가 립싱크하는 "Dragostea Din Tei" 웹캠 영상. 초기 인터넷 밈의 원조. 2004.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Double Rainbow',
 array['double rainbow','쌍무지개','what does it mean'],
 '쌍무지개를 보고 감격해 "이게 무슨 의미야!"라 외치는 영상 밈. 2010.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Leave Britney Alone',
 array['leave britney alone','브리트니 내버려둬','chris crocker'],
 '크리스 크로커가 울며 "브리트니를 내버려둬!"라 절규하는 영상 밈. 2007.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Star Wars Kid',
 array['star wars kid','스타워즈 키드','광선검 소년'],
 '광선검 흉내를 내는 소년의 영상이 유출돼 초기 바이럴 밈이 됨. 2003.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Dramatic Chipmunk',
 array['dramatic chipmunk','극적인 다람쥐','홱 돌아보는 프레리도그'],
 '프레리도그가 극적인 음악과 함께 홱 돌아보는 짧은 영상. 반전 강조 밈. 2007.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Sneezing Panda',
 array['sneezing panda','재채기 판다','놀란 엄마판다'],
 '아기 판다의 재채기에 엄마 판다가 화들짝 놀라는 영상 밈. 2006.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Grumpy Cat RIP',
 array['grumpy cat rip','심술 고양이 추모','tardar sauce'],
 '심술 고양이 타르다르 소스의 별세를 추모하며 회자되는 밈.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Keyboard Cat Play Off',
 array['play him off','키보드 고양이','연주 마무리'],
 '망한 장면 뒤 "Play him off, Keyboard Cat"으로 연주하는 고양이를 붙이는 밈. 2007.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Salt Bae Sprinkle',
 array['salt bae','소금 뿌리기','누스렛 포즈'],
 '셰프 누스렛이 팔꿈치로 소금을 흩뿌리는 포즈. 폼나게 마무리할 때 쓰는 포즈 밈. 2017.',
 array['#고전','#유명인','#미국','#스테디'],
 'new', 'celebrity', 'https://knowyourmeme.com/', null),

('Overly Excited Guy',
 array['overly excited','지나치게 신난 남자','kazoo kid'],
 '지나치게 흥분한 인물 짤로 과한 기대·열광을 표현하는 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Gordon Ramsay Idiot Sandwich',
 array['idiot sandwich','고든 램지','바보 샌드위치'],
 '고든 램지가 빵 사이에 얼굴을 끼우며 "idiot sandwich"라 호통치는 장면. 답답함을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Confused Nick Young',
 array['confused nick young','물음표 닉 영','question marks'],
 '농구선수 닉 영의 얼굴 주위에 물음표가 떠다니는 GIF. 어리둥절함을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Blinking White Guy',
 array['blinking white guy','깜빡이는 남자','drew scanlon'],
 '드루 스캔런이 믿기지 않는 듯 눈을 끔뻑이는 GIF. 황당함을 표현하는 반응 GIF.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Michael Jordan Crying',
 array['crying jordan','우는 조던','패배자 합성'],
 '눈물 흘리는 마이클 조던 얼굴을 패자에게 합성하는 스포츠 조롱 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Tom Cruise Laugh',
 array['tom cruise laugh','톰 크루즈 웃음','광기 웃음'],
 '톰 크루즈의 과장된 웃음 짤. 어색하거나 광기 어린 웃음을 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Distraction Dance',
 array['distraction dance','fortnite 춤','default dance'],
 '포트나이트 기본 춤(default dance)이 승리·조롱의 상징으로 밈화. 2018.',
 array['#고전','#게임','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Weird Flex But OK',
 array['weird flex but ok','이상한 자랑','flex 밈'],
 '굳이 안 해도 될 자랑을 하는 이에게 "이상한 자랑이지만 뭐 그래"라 반응하는 밈. 2018.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('And I Took That Personally',
 array['took that personally','마이클 조던','개인적으로 받아들임'],
 '마이클 조던 다큐 짤로 "그래서 나는 그걸 개인적으로 받아들였지"라 결의를 표현하는 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('They Don''t Know Party',
 array['they dont know','파티 구석 남자','쟤들은 모르지'],
 '파티에서 홀로 선 남자가 "쟤들은 내가 X인 걸 모르지"라 생각하는 자조 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('POV You''re',
 array['pov youre','시점 밈','1인칭 상황'],
 '"POV: 네가 X한 상황"으로 시청자를 1인칭에 놓는 틱톡·릴스 상황극 포맷.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Nobody Wants To Work Anymore',
 array['nobody wants to work','아무도 일 안 해','세대 논쟁'],
 '"요즘 아무도 일하기 싫어한다"는 문구를 옛 사진에 붙여 세대 담론을 비꼬는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Aged Like Milk',
 array['aged like milk','우유처럼 상함','빗나간 예측'],
 '시간이 지나 형편없어진 발언·예측을 "우유처럼 상했다"라 하는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Aged Like Fine Wine',
 array['aged like fine wine','와인처럼 숙성','시간이 증명'],
 '시간이 지나 더욱 빛을 발한 것을 "고급 와인처럼 숙성됐다"라 하는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Bro Really Said',
 array['bro really said','형이 진짜 그랬어','어이없는 발언'],
 '"형이 진짜로 X라고 했어"라며 상대의 황당한 발언을 인용해 비꼬는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('The Audacity',
 array['the audacity','뻔뻔함','무슨 배짱'],
 '누군가의 뻔뻔한 행동에 "the audacity(그 배짱하고는)"라 어이없어하는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Not The',
 array['not the','하필 그거','놀란 반응'],
 '"하필 그 X이라니(not the X)"라며 황당하거나 웃긴 지점을 콕 집는 유행어.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Girl Help',
 array['girl help','도와줘 얘야','곤란 유행어'],
 '곤란한 상황에서 "girl help(얘 좀 도와줘)"라 외치는 자조적 유행어.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Not Me',
 array['not me','설마 내가','자조 유행어'],
 '"설마 내가 X하고 있는 건 아니겠지(not me X-ing)"라며 자조하는 유행어 포맷.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Tell Me Without Telling Me',
 array['tell me without telling me','말 안 하고 말해봐','챌린지 포맷'],
 '"X라고 직접 말하지 않고 X임을 보여줘"라는 참여형 챌린지 포맷. 2020~2021.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('It''s Corn Kid',
 array['its corn','옥수수 소년','corn kid'],
 '한 소년이 옥수수를 예찬한 인터뷰가 노래로 리믹스된 "It''s Corn" 밈. 순수한 기쁨의 상징. 2022.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Corn Kid Big Lumps',
 array['big lumps','옥수수 혹','corn song'],
 '옥수수 소년의 "it has the juice, big lumps" 가사가 밈으로 확산.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Berries And Cream',
 array['berries and cream','베리와 크림','little lad'],
 '옛 광고의 "berries and cream" 춤과 노래가 틱톡에서 역주행한 밈. 2021.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Oh No Cringe',
 array['oh no','오 노','kombucha girl 오노'],
 '무언가를 접하고 "오 노…" 하며 물러서는 반응 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Zoomer vs Boomer',
 array['zoomer vs boomer','주머 vs 부머','세대 대결'],
 'Z세대 워잭과 베이비부머 워잭을 대비시켜 세대 차이를 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Big Chungus',
 array['big chungus','빅 청거스','통통 벅스버니'],
 '통통하게 부푼 벅스 버니 이미지 "빅 청거스". 부조리 유머의 상징. 2018.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Cheems',
 array['cheems','침스','울먹이는 시바'],
 '말투가 어눌한 시바견 밈 캐릭터 "Cheems". 약하거나 요즘 세태를 표현할 때 씀.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Swole Doge',
 array['swole doge','근육 도지','buff doge'],
 '근육질로 합성한 도지. 강함이나 과거의 위엄을 표현하며 Cheems와 대비됨.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Walter Dog',
 array['walter dog','월터','놀란 불독'],
 '눈이 튀어나올 듯 놀란 불독 "Walter". 경악·황당함을 표현하는 반응짤.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Bingus',
 array['bingus','빙거스','털 없는 고양이'],
 '털 없는 스핑크스 고양이 "Bingus". 못생겼지만 사랑스러운 인터넷 마스코트 밈.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Floppa',
 array['floppa','플로파','카라칼 고양이'],
 '큰 귀의 카라칼 "Floppa". Bingus와 함께 인터넷 고양이 밈으로 사랑받음.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Maxwell The Cat',
 array['maxwell cat','맥스웰 고양이','스핀 고양이'],
 '빙글빙글 도는 회색 고양이 "Maxwell". 각종 음악에 합성돼 유행한 밈.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Banana Cat',
 array['banana cat','바나나 고양이','우는 바나나 고양이'],
 '바나나 껍질 속에서 우는 AI 고양이 "Banana Cat". 애처로운 반응짤로 확산. 2023.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Happy Cat Happy Happy',
 array['happy cat','해피 캣','웃는 고양이 노래'],
 '"happy happy happy cat" 노래와 함께 웃는 고양이 밈. 밝은 분위기를 표현. 2023.',
 array['#고전','#동물','#미국','#스테디'],
 'new', 'animal', 'https://knowyourmeme.com/', null),

('Impostor Vent',
 array['impostor vent','벤트하는 임포스터','among us 킬'],
 '어몽어스에서 임포스터가 벤트로 사라지는 장면. 몰래 빠져나가거나 정체를 숨길 때 쓰는 밈.',
 array['#고전','#게임','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Emergency Meeting',
 array['emergency meeting','긴급 회의','among us 소집'],
 '어몽어스 긴급 회의 버튼 장면. 갑작스레 문제를 제기·소집할 때 쓰는 밈.',
 array['#고전','#게임','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Where Impostor',
 array['where impostor','임포스터 어디','의심 밈'],
 '어몽어스에서 누가 임포스터인지 의심하는 상황을 표현하는 밈.',
 array['#고전','#게임','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Kanye Shrug',
 array['kanye shrug','칸예 어깨 으쓱','idk'],
 '칸예 웨스트가 어깨를 으쓱하는 장면. "글쎄, 몰라"라는 무심한 반응을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Kanye Staring',
 array['kanye staring','응시하는 칸예','무표정 칸예'],
 '칸예가 무표정하게 정면을 응시하는 장면. 어이없거나 시큰둥한 반응을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Drake No Yes',
 array['drake no yes','드레이크 거부 승인','hotline bling'],
 '드레이크가 위 칸에서 거부, 아래 칸에서 승인하는 2단 비교 템플릿.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Surprised Baby',
 array['surprised baby','놀란 아기','충격 아기'],
 '눈이 휘둥그레진 아기 사진. 충격이나 놀라움을 표현하는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Michael Scott That''s What She Said',
 array['thats what she said','마이클 스콧','the office 드립'],
 '더 오피스의 마이클 스콧이 "That''s what she said" 농담을 던지는 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Jim Halpert Stare',
 array['jim halpert stare','짐 응시','카메라 보기'],
 '더 오피스의 짐이 어이없어 카메라를 빤히 쳐다보는 장면. 무언의 어이없음을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Dwight Schrute False',
 array['false dwight','드와이트 false','틀렸어'],
 '더 오피스의 드와이트가 "False."라 단호히 반박하는 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Stanley Parable',
 array['stanley','the office 스탠리','무관심 스탠리'],
 '더 오피스의 스탠리가 무심하고 시큰둥한 반응을 보이는 밈.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Kermit Sipping Tea',
 array['kermit tea','차 마시는 케르밋','none of my business'],
 '케르밋이 차를 홀짝이며 "근데 내 알 바 아니지"라 능청 떠는 장면.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Spongebob Rainbow Imagination',
 array['imagination rainbow','상상 무지개','스폰지밥 손'],
 '스폰지밥이 손으로 무지개를 그리며 "상상~"이라 말하는 장면. 현실도피를 비꼴 때 씀.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Distressed Pikachu',
 array['distressed pikachu','당황 피카츄','입 벌린 피카츄'],
 '입을 벌리고 눈이 커진 피카츄. 뻔한 결과에 새삼 놀라는 척할 때 쓰는 반응짤.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Bufo Cane Toad',
 array['bufo','부포','개구리 이모지'],
 '디스코드 등에서 쓰이는 개구리(두꺼비) 이모지 세트 "Bufo". 다양한 감정을 표현.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Weird Al',
 array['weird al','위어드 알','패러디 음악'],
 '위어드 알 얀코빅의 패러디 곡·이미지가 인터넷 유머의 고전으로 회자되는 밈.',
 array['#고전','#유명인','#미국','#스테디'],
 'new', 'celebrity', 'https://knowyourmeme.com/', null),

('Shrek Ogre',
 array['shrek','슈렉','ogres are like onions'],
 '슈렉의 각종 장면·대사("양파처럼 여러 겹")가 부조리 밈 문화의 아이콘으로 자리 잡음.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/shrek-ogre.webp'),

('Shrek Somebody Once Told Me',
 array['all star','somebody once told me','슈렉 오프닝'],
 '슈렉 오프닝 곡 "All Star"가 각종 부조리 편집 밈의 단골 소재가 됨.',
 array['#고전','#사운드','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/shrek-somebody-once-told-me.png'),

('Thomas The Tank Engine',
 array['thomas the tank engine','토마스 기차','합성 단골'],
 '토마스와 친구들 기차 캐릭터가 온갖 게임·영상에 합성되는 부조리 밈의 단골.',
 array['#고전','#캐릭터','#미국','#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/thomas-the-tank-engine.jfif'),

('John Cena Bing Chilling',
 array['bing chilling','존 시나 아이스크림','중국어 존 시나'],
 '존 시나가 어눌한 중국어로 아이스크림을 소개하는 영상 "bing chilling" 밈. 2021.',
 array['#고전','#영상','#미국','#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/john-cena-bing-chilling.webp'),

('You Wouldn''t Get It',
 array['you wouldnt get it','넌 몰라','안경 남자'],
 '"이건 네가 이해 못 해"라며 잘난 척하는 힙스터 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/you-wouldnt-get-it.jfif'),

('Uno Reverse Card',
 array['uno reverse','우노 리버스','되받아치기'],
 '우노 리버스 카드로 상황을 상대에게 되돌리는 밈. "그대로 돌려준다"를 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/uno-reverse-card.webp'),

('Infinite IQ',
 array['infinite iq','무한 지능','4d chess'],
 '겉보기엔 멍청하지만 실은 초고차원 전략이라며 반어적으로 치켜세우는 "infinite IQ" 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/infinite-iq.jfif'),

('Bro Woke Up And Chose',
 array['chose violence','폭력을 택함','작정하고 나옴'],
 '"쟤 오늘 일어나서 폭력을 택했네(chose violence)"라며 작정한 태도를 표현하는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/bro-woke-up-and-chose.jfif'),

('Everyone Liked That',
 array['everyone liked that','다들 좋아함','fallout 좋아요'],
 '게임 폴아웃의 "Everyone liked that" 알림을 활용해 만장일치 호응을 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/everyone-liked-that.jpg'),

('Nobody Liked That',
 array['nobody liked that','아무도 안 좋아함','fallout 싫어요'],
 '폴아웃의 "Nobody liked that" 알림으로 아무도 반기지 않는 상황을 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Speech 100',
 array['speech 100','화술 100','skyrim 설득'],
 '스카이림의 "Speech 100" 밈. 말도 안 되는 설득이 통하는 상황을 표현.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/speech-100.jfif'),

('Press F',
 array['press f','경의를 표하려면 f','pay respects'],
 '콜 오브 듀티의 "F를 눌러 경의를 표하라"에서 온 밈. 안타까운 일에 "F"를 치는 관습.',
 array['#고전','#게임','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/press-f-meme2.jfif'),

('Achievement Unlocked',
 array['achievement unlocked','업적 달성','xbox 알림'],
 '게임 업적 달성 알림을 패러디해 사소하거나 엉뚱한 성취를 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/achievement-unlocked.jfif'),

('Loading Bar',
 array['loading bar','로딩바','기다림 밈'],
 '느리게 차오르는 로딩바 이미지로 지루한 기다림이나 진행을 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/loading-bar.webp'),

('Windows Error',
 array['windows error','윈도우 오류창','블루스크린'],
 '윈도우 오류 팝업·블루스크린을 패러디해 무언가 잘못됐음을 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/windows-error.jpg'),

('404 Not Found',
 array['404','낫 파운드','없음 밈'],
 '"404 Not Found" 오류를 빌려 무언가가 존재하지 않음을 재치 있게 표현하는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/404-not-found.jfif'),

('Task Manager End Task',
 array['end task','작업 끝내기','강제 종료'],
 '작업 관리자로 프로그램을 강제 종료하는 걸 빗대 무언가를 끝장낼 때 쓰는 밈.',
 array['#고전','#포맷','#미국','#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/task-manager-end-task.jfif'),

('Ctrl Z',
 array['ctrl z','되돌리기','undo 밈'],
 '실수를 되돌리고 싶을 때 "Ctrl+Z"를 외치는 밈.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/ctrl-z.jpg'),

('This Is Fine Dog Fire',
 array['this is fine dog','불타는 방 강아지','괜찮아'],
 '불길 속에서 커피를 든 강아지가 "이거 괜찮아"라 말하는 웹툰 컷. 애써 태연한 척을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/this-is-fine-dog-fire.jpg'),

('Bernie Sanders Chair',
 array['bernie chair','버니 의자','벙어리장갑'],
 '취임식에서 벙어리장갑 끼고 접이식 의자에 앉은 버니 샌더스. 온갖 배경에 합성됨. 2021.',
 array['#고전','#합성','#미국','#스테디'],
 'new', 'celebrity', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/bernie-sanders-chair.jfif'),

('Guy Staring At Screen',
 array['guy staring at screen','화면 응시 남자','현타 남자'],
 '화면을 멍하니 응시하는 남자 짤. 어이없거나 현타 온 순간을 표현.',
 array['#고전','#반응짤','#미국','#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/guy-staring-at-screen.jfif'),

('Salute Emoji',
 array['salute emoji','경례 이모지','🫡'],
 '존경·수긍을 표현하는 경례 이모지 🫡가 밈적 반응으로 널리 쓰이는 표현.',
 array['#고전','#유행어','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/salute-emoji.jfif'),

('Standing On Business Meme',
 array['standing on business','자기 일에 진심','진지 모드'],
 '"standing on business(할 일에 진지하게 임한다)"를 강조하는 유행어 밈. 2024.',
 array['#유행어','#틱톡','#미국','#2024'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/standing-on-business-meme.jfif'),

('Aura Points Meme',
 array['aura points','아우라 포인트','간지 점수'],
 '행동의 멋짐 여부에 "aura +1000 / -1000"처럼 점수를 매기는 밈. 2024~2025.',
 array['#유행어','#GenAlpha','#미국','#2025'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/aura-points-meme.jfif'),

('Looksmaxxing Meme',
 array['looksmaxxing','룩스맥싱','외모 극대화'],
 '외모를 극한까지 끌어올린다는 "looksmaxxing" 밈. mewing 등과 엮여 자기관리 문화를 반쯤 조롱.',
 array['#유행어','#GenAlpha','#미국','#2024'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/looksmaxxing-meme.jfif'),

('Mewing Shush',
 array['mewing','뮤잉','턱 쓸며 조용'],
 '혀를 입천장에 붙여 턱선을 만든다는 "mewing"이 밈화. 말 대신 턱을 쓸며 조용히 하라는 제스처로도 씀.',
 array['#유행어','#GenAlpha','#미국','#2024'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/mewing-shush.png'),

('Fanum Tax Meme',
 array['fanum tax','파넘 택스','음식 뺏기'],
 '스트리머 Fanum이 친구 음식을 뺏어 먹는 데서 온 "Fanum tax". 남의 것을 슬쩍 챙기는 행위를 뜻함.',
 array['#유행어','#GenAlpha','#미국','#2024'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/fanum-tax-meme.jfif'),

('Gyatt Meme',
 array['gyatt','갓','gen alpha 감탄'],
 '"God damn"에서 온 Gen Alpha 감탄사 "gyatt". 놀람·감탄을 과장해 표현.',
 array['#유행어','#GenAlpha','#미국','#2024'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/gyatt-meme.png'),

('Rizzler',
 array['rizzler','리즐러','매력꾼'],
 '"rizz(이성을 끄는 매력)"가 뛰어난 사람을 "rizzler"라 부르는 파생 슬랭.',
 array['#유행어','#GenAlpha','#미국','#2024'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/rizzler.jfif'),

('Only In Ohio',
 array['only in ohio','오직 오하이오','괴상한 곳'],
 '"오직 오하이오에서만" 기괴한 일이 벌어진다는 부조리 밈. "이상한 곳"의 대명사.',
 array['#유행어','#GenAlpha','#미국','#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/only-in-ohio.jfif'),

('Werid-AI',
 array['werid ai', '위어드 에이아이', 'AI 오타 짤'],
 'AI로 생성된 기괴하고 어색한 이미지에 붙는 밈. "weird"를 일부러 "werid"로 잘못 표기하는 것이 특징.',
 array['#AI', '#미국', '#2025'],
 'new', 'format', 'https://knowyourmeme.com/', 'https://faofjruxrabdbtesrkub.supabase.co/storage/v1/object/public/media/en-memes/werid-ai.jpg')
on conflict (name) do nothing;
