-- ═══════════════════════════════════════════════════════════════
--  미국(영어권) 밈 시드 100개
--  고전 스테디 밈 + 2024~2026 신상 밈 혼합
--  category: 미국식 자유 분류 (reaction / character / catchphrase /
--            video / brainrot / celebrity / animal / format 등)
--  해시태그에 #미국 필수 포함
--  출처: 여러 밈을 묶은 대표 출처 (Know Your Meme, Wikipedia,
--        Meme Hall of Fame, NBC News, FOX, tjTODAY 등)
-- ═══════════════════════════════════════════════════════════════

insert into memes (name, keywords, description, tags, status, category, source, photo_url) values

('Rickroll',
 array['rickroll', 'rick astley', 'never gonna give you up'],
 '릭 애슬리의 1987년 곡 "Never Gonna Give You Up" 뮤비 링크로 낚는 장난. 무언가 볼 줄 알고 클릭했더니 이 노래가 나오면 "릭롤 당했다". 2007년부터 시작돼 영어권 인터넷 최장수 낚시 밈이 됨.',
 array['#고전', '#낚시', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://www.meme-hall-of-fame.com/', null),

('Doge',
 array['doge', 'such wow', 'shiba inu', 'much meme'],
 '눈을 옆으로 흘기는 시바견 카보스의 사진에 코믹산스 글씨로 "such wow", "much X", "very Y" 같은 엉터리 영어를 붙이는 밈. 2013년 폭발, 도지코인(Dogecoin)까지 만들어낸 밈계의 헤비급 챔피언.',
 array['#고전', '#동물', '#미국', '#스테디'],
 'new', 'animal', 'https://www.meme-hall-of-fame.com/', null),

('Distracted Boyfriend',
 array['distracted boyfriend', '한눈파는 남친', '한눈파는 남자친구'],
 '여자친구와 걷던 남자가 지나가는 다른 여자를 대놓고 돌아보고, 여친은 어이없어하는 스톡 사진. 세 인물에 라벨을 붙여 "새것에 눈 돌리는 상황"을 표현. 2017년 대유행.',
 array['#고전', '#라벨링', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Drake Hotline Bling',
 array['drake', 'hotline bling', '드레이크'],
 '드레이크가 위쪽 칸에서는 손사래 치며 거부하고, 아래 칸에서는 흡족하게 가리키는 2단 포맷. "이건 싫고 저건 좋다"를 비교할 때 쓰는 국민 템플릿. 2015년.',
 array['#고전', '#비교', '#미국', '#스테디'],
 'new', 'format', 'https://www.meme-hall-of-fame.com/', null),

('Surprised Pikachu',
 array['surprised pikachu', '놀란 피카츄', '피카츄'],
 '입을 벌리고 눈이 휘둥그레진 피카츄 캡처. "뻔한 결과인데 막상 닥치니 놀라는 척" 하는 상황에 붙이는 반응짤. 2018년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Woman Yelling at a Cat',
 array['woman yelling at a cat', '고양이한테 소리지르는 여자', '흰 고양이 식탁'],
 '리얼리티쇼에서 여자가 손가락질하며 울부짖는 장면과, 식탁 앞에 앉아 시큰둥한 흰 고양이(스맛지)를 나란히 붙인 2단 밈. 감정적인 쪽 vs 무심한 쪽 대립을 표현. 2019년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Expanding Brain',
 array['expanding brain', '뇌 확장', '갤럭시 브레인'],
 '작은 뇌부터 빛나는 우주 뇌까지 단계별로 커지는 4~5칸 포맷. 위에서 아래로 갈수록 "더 대단해 보이지만 실은 더 멍청한" 아이디어를 나열하는 반어적 밈. 2017년.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://www.meme-hall-of-fame.com/', null),

('Mocking SpongeBob',
 array['mocking spongebob', '조롱 스폰지밥', '대문자소문자'],
 '스폰지밥이 닭처럼 몸을 숙인 우스꽝스러운 장면에 "aLtErNaTiNg CaPs"(대소문자 번갈아)로 문장을 써서 상대 말을 비꼬는 밈. 2017년.',
 array['#고전', '#조롱', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Change My Mind',
 array['change my mind', '내 생각을 바꿔봐', '스티븐 크라우더'],
 '스티븐 크라우더가 캠퍼스에 "탁자+현수막"을 놓고 앉은 사진. 현수막 문구를 논쟁적/황당한 주장으로 바꿔 "반박해봐"라고 도발하는 템플릿. 2018년.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://www.meme-hall-of-fame.com/', null),

('Stonks',
 array['stonks', '스톤크스', '주식'],
 '정장 입은 밈맨(Meme Man)이 상승 화살표 앞에 선 이미지에 "STONKS"라 적은 밈. 금전적으로 이득 봤거나, 반대로 어이없는 손해를 봤을 때 반어적으로 사용. 2017년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Always Has Been',
 array['always has been', '늘 그래왔지', '우주비행사 총'],
 '우주에서 지구를 보던 우주비행사가 "Wait, it''s all X?"라 묻고, 뒤의 동료가 총을 겨누며 "Always has been"이라 답하는 2컷 만화. 충격적 진실을 폭로할 때 씀. 2020년.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://www.meme-hall-of-fame.com/', null),

('Evil Kermit',
 array['evil kermit', '이블 커밋', '어두운 커밋'],
 '커밋과, 두건을 쓴 어두운 커밋이 마주 선 장면. "이성적인 나 vs 유혹하는 나쁜 나"의 내적 갈등을 표현하는 템플릿. 2016년.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://www.meme-hall-of-fame.com/', null),

('GigaChad',
 array['gigachad', '기가차드', '차드'],
 '극단적으로 각진 턱선의 흑백 남성 사진. 이상적이고 압도적으로 "옳은" 행동/취향을 상징하는 밈. 2017년 등장 후 지금도 반어·진지 양쪽으로 활발히 사용.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Wojak',
 array['wojak', '워잭', 'feels guy'],
 '단순한 선으로 그린 대머리 남자 얼굴. 공허하거나 우울한 감정을 대변하며, 수많은 파생형(Doomer, Coomer 등)을 낳은 인터넷 감정 표현의 원형. 2010년.',
 array['#고전', '#감정', '#미국', '#스테디'],
 'new', 'character', 'https://www.meme-hall-of-fame.com/', null),

('NPC Wojak',
 array['npc wojak', 'NPC', '엔피씨'],
 '무표정한 회색 워잭. 게임 속 배경 캐릭터(NPC)처럼 스스로 생각 없이 정해진 말만 반복하는 사람을 비꼬는 밈. 2018년.',
 array['#고전', '#조롱', '#미국', '#스테디'],
 'new', 'character', 'https://www.meme-hall-of-fame.com/', null),

('Coffin Dance',
 array['coffin dance', '관짝춤', '가나 관짝소년단'],
 '가나의 장례식에서 정장 입은 남자들이 관을 메고 춤추는 영상. 사고·실패 영상 끝에 붙여 "이제 죽었다"를 유쾌하게 표현. 2020년 코로나 시기 폭발.',
 array['#고전', '#영상', '#미국', '#스테디'],
 'new', 'video', 'https://www.meme-hall-of-fame.com/', null),

('Among Us',
 array['among us', '어몽어스', 'sus', 'imposter'],
 '게임 어몽어스의 콩알 우주인 캐릭터와 "sus(수상하다)", "impostor" 개념이 밈화. 누군가 의심스러울 때 "너 sus해"라고 쓰는 표현으로 정착. 2020년.',
 array['#고전', '#게임', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://www.meme-hall-of-fame.com/', null),

('This Is Fine',
 array['this is fine', '이거 괜찮아', '불타는 방 강아지'],
 '불길에 휩싸인 방 안에서 강아지가 커피를 들고 "This is fine"이라 말하는 웹툰 컷. 상황이 엉망인데 애써 태연한 척할 때 쓰는 대표 밈. 2013년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Grumpy Cat',
 array['grumpy cat', '심술 고양이', '타르드 소스'],
 '유전적 부정교합으로 늘 불만스러운 표정인 고양이 타르드 소스. "No." 같은 시니컬한 문구와 함께 쓰인 2010년대 초 대표 동물 밈. 2012년.',
 array['#고전', '#동물', '#미국', '#스테디'],
 'new', 'animal', 'https://www.meme-hall-of-fame.com/', null),

('Hide the Pain Harold',
 array['hide the pain harold', '고통 숨기는 해럴드', '해럴드'],
 '스톡 사진 모델 할아버지(안드라스 아라토)가 어색하게 웃지만 눈에는 고통이 서린 표정. 억지로 괜찮은 척하는 상황에 쓰는 밈. 2011년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Bad Luck Brian',
 array['bad luck brian', '불운의 브라이언'],
 '치아교정기를 낀 채 스웨터 조끼를 입고 어색하게 웃는 졸업사진. "최악의 타이밍에 최악의 일이 벌어지는" 불운을 묘사하는 어드바이스 애니멀 밈. 2012년.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('One Does Not Simply',
 array['one does not simply', '반지의 제왕 보로미르'],
 '반지의 제왕 보로미르가 "One does not simply walk into Mordor"라 말하는 장면. "그냥 쉽게 X할 수 있는 게 아니다"를 표현하는 템플릿. 2012년.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://www.meme-hall-of-fame.com/', null),

('Nyan Cat',
 array['nyan cat', '냥캣', '팝타르트 고양이'],
 '몸통이 팝타르트인 픽셀 고양이가 무지개를 뿜으며 우주를 나는 GIF. 반복되는 "냥냥" 배경음과 함께 2011년 유행한 초기 인터넷 GIF 밈.',
 array['#고전', '#GIF', '#미국', '#스테디'],
 'new', 'animal', 'https://www.meme-hall-of-fame.com/', null),

('Sad Keanu',
 array['sad keanu', '슬픈 키아누', '키아누 리브스'],
 '벤치에서 홀로 샌드위치를 든 키아누 리브스의 파파라치 사진. 쓸쓸하거나 처량한 감정에 붙여 쓰며, 오히려 그를 좋아하는 정서로 번짐. 2010년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Leonardo DiCaprio Cheers',
 array['leo cheers', '디카프리오 건배', '위대한 개츠비'],
 '영화 위대한 개츠비에서 레오나르도 디카프리오가 샴페인 잔을 들고 카메라를 보며 건배하는 장면. 무언가를 축하하거나 비꼴 때 쓰는 반응짤. 2013년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Success Kid',
 array['success kid', '성공한 아기', '주먹 쥔 아기'],
 '모래를 한 줌 쥐고 결연한 표정으로 주먹 쥔 아기 사진. 작지만 짜릿한 성공의 순간에 붙이는 밈. 2007년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Pepe the Frog',
 array['pepe', '페페', '개구리 페페'],
 '만화 "Boy''s Club"의 개구리 캐릭터. "feels good man" 대사에서 출발해 sad/smug 등 무수한 감정 변형을 낳은 인터넷 대표 캐릭터 밈. 2005년.',
 array['#고전', '#감정', '#미국', '#스테디'],
 'new', 'character', 'https://www.meme-hall-of-fame.com/', null),

('Trollface',
 array['trollface', '트롤페이스', 'problem'],
 '악랄하게 히죽대는 손그림 얼굴. 상대를 골탕 먹이거나 트롤링할 때의 심보를 상징. "Problem?"과 함께 2008년 유행한 랄로 만화의 상징.',
 array['#고전', '#조롱', '#미국', '#스테디'],
 'new', 'character', 'https://www.meme-hall-of-fame.com/', null),

('Disaster Girl',
 array['disaster girl', '재난 소녀', '불타는 집 소녀'],
 '불타는 집 앞에서 카메라를 향해 묘하게 웃는 어린 소녀(조 로스). 마치 자기가 저지른 듯한 뉘앙스로 "은근한 악의"를 표현하는 밈. 2005년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Roll Safe',
 array['roll safe', '관자놀이 두드리기', '똑똑한 척'],
 '남자가 관자놀이를 손가락으로 톡톡 두드리는 장면. "이렇게 하면 문제가 안 생기지"라며 그럴듯하지만 실은 허점 있는 꼼수를 제시할 때 쓰는 밈. 2017년.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Is This a Pigeon',
 array['is this a pigeon', '이게 비둘기인가', '나비 로봇'],
 '애니메이션 속 로봇이 나비를 가리키며 "Is this a pigeon?"이라 묻는 장면. 무언가를 어이없이 잘못 알아볼 때 라벨을 붙여 쓰는 템플릿. 2011년 애니, 2018년 밈화.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Two Buttons',
 array['two buttons', '두 개의 버튼', '땀 흘리는 남자'],
 '두 개의 버튼 앞에서 어느 것을 누를지 식은땀 흘리는 남자 만화. 양립하기 어려운 두 선택 사이의 갈등을 표현하는 템플릿. 2018년.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Gru''s Plan',
 array['grus plan', '그루의 계획', '슈퍼배드 화이트보드'],
 '슈퍼배드의 그루가 화이트보드로 4단계 계획을 발표하다가, 마지막 칸에서 예상치 못한 반전을 보고 굳는 4컷 밈. 계획이 부메랑으로 돌아올 때 씀. 2020년.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Sigma Male',
 array['sigma', '시그마', '시그마 남성'],
 '"알파도 베타도 아닌, 무리 밖의 독고다이 남성"을 뜻하는 반쯤 진지 반쯤 조롱하는 개념 밈. 패트릭 베이트먼 등 영화 캐릭터 편집과 함께 유행. 2021년.',
 array['#고전', '#조롱', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('POV Format',
 array['pov', '피오브이', '시점 밈'],
 '"POV: 네가 X한 상황"처럼 시청자를 1인칭 시점에 놓고 특정 상황을 연출하는 틱톡·릴스 포맷. 공감형 상황극의 표준 틀로 정착.',
 array['#포맷', '#틱톡', '#미국', '#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('It''s Gonna Be May',
 array['its gonna be may', '저스틴 팀버레이크 5월'],
 '엔싱크의 저스틴 팀버레이크 얼굴에 "It''s gonna be May"를 붙인 밈. 곡 "It''s Gonna Be Me"의 발음을 이용해 매년 4월 말 부활하는 계절 밈.',
 array['#고전', '#계절밈', '#미국', '#스테디'],
 'new', 'celebrity', 'https://www.socialchamp.com/blog/social-media-memes/', null),

('Krispy Kreme Crispy',
 array['krispy kreme', '크리스피 크림', '크리스피 여자'],
 '한 여성이 "Krispy Kreme이 정말 crispy(바삭)한 줄 알았다"며 순진하게 되묻는 클립. 매년 부활해 사람들이 또 속아 넘어가는 롱런 밈.',
 array['#고전', '#영상', '#미국', '#스테디'],
 'new', 'video', 'https://www.bu.edu/articles/2025/the-memes-that-got-us-through-2025/', null),

('Michael Scott No',
 array['michael scott no', '마이클 스콧', '노 갓 플리즈'],
 '더 오피스에서 마이클 스콧이 "No! No! God, please no!"라고 절규하는 장면. 최악의 소식을 들었을 때의 절망을 표현하는 반응짤.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

-- ═══════ 2024 밈 ═══════

('Skibidi Toilet',
 array['skibidi toilet', '스키비디 토일렛', '변기'],
 '유튜버 DaFuq!?Boom!의 시리즈로, 변기에서 사람 머리가 튀어나와 노래하며 카메라머리 인간들과 싸우는 초현실 애니. Gen Alpha 슬랭 "skibidi"의 근원. 2023~2024 폭발.',
 array['#유튜브', '#브레인롯', '#미국', '#GenAlpha'],
 'new', 'video', 'https://www.nbcnews.com/pop-culture/best-memes-moments-2024-brat-demure-hawk-tuah-rcna181956', null),

('Hawk Tuah',
 array['hawk tuah', '호크투아', '헤일리 웰치'],
 '길거리 인터뷰에서 헤일리 웰치가 특유의 남부 억양으로 던진 야한 농담 "hawk tuah"가 순식간에 여름 유행어가 되며 그녀를 하루아침에 스타로 만든 클립. 2024 여름.',
 array['#유행어', '#영상', '#미국', '#2024'],
 'new', 'celebrity', 'https://www.nbcnews.com/pop-culture/best-memes-moments-2024-brat-demure-hawk-tuah-rcna181956', null),

('Brat Summer',
 array['brat', '브랫', '브랫 서머', 'charli xcx'],
 '찰리 XCX의 앨범 "brat"의 라임그린 표지와 미감이 하나의 라이프스타일 밈으로 확산. 당당하고 파티지향적이며 약간 지저분한 "brat" 태도가 2024 여름을 정의.',
 array['#음악', '#라이프스타일', '#미국', '#2024'],
 'new', 'celebrity', 'https://www.nbcnews.com/pop-culture/best-memes-moments-2024-brat-demure-hawk-tuah-rcna181956', null),

('Very Demure Very Mindful',
 array['very demure', '베리 디뮤어', 'jools lebron'],
 '틱토커 줄스 르브론이 "아주 조신하게, 아주 신중하게(very demure, very mindful)" 처신한다고 설명하는 영상에서 시작. 과장된 우아함을 표현하는 유행어. 2024.',
 array['#유행어', '#틱톡', '#미국', '#2024'],
 'new', 'catchphrase', 'https://www.nbcnews.com/pop-culture/best-memes-moments-2024-brat-demure-hawk-tuah-rcna181956', null),

('Moo Deng',
 array['moo deng', '무뎅', '아기 하마', '피그미 하마'],
 '태국 카오키여우 동물원의 아기 피그미하마 무뎅. 통통 튀는 표정과 몸짓이 짤로 퍼지며 세계적 인기를 끈 2024 대표 동물 밈.',
 array['#동물', '#귀여움', '#미국', '#2024'],
 'new', 'animal', 'https://www.fox9.com/news/best-memes-2024', null),

('AI Slop',
 array['ai slop', 'AI 슬롭', '쉬림프 지저스'],
 'AI로 대량 생산된 조악하고 기괴한 이미지들(새우 예수, 이상한 아기 등)을 통칭하는 밈이자 비판어. 페이스북 등에 범람하며 AI 윤리 논쟁을 촉발. 2024.',
 array['#AI', '#비판', '#미국', '#2024'],
 'new', 'format', 'https://www.fox9.com/news/best-memes-2024', null),

('Looking at Wrist',
 array['looking at wrist', '손목 보기', '시계 확인'],
 '누군가 손목의 (없는) 시계를 보는 척하는 반응. 상대가 뻔한 소리를 하거나 시간 낭비할 때 "그래서 언제 끝나?"를 표현. 스테디하게 재등장.',
 array['#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

-- ═══════ 2025 밈 ═══════

('Tralalero Tralala',
 array['tralalero tralala', '트랄랄레로', '나이키 신은 상어'],
 '파란 나이키 운동화를 신은 세 다리 상어 AI 캐릭터. 이탈리안 브레인롯의 대표 격으로, 엉터리 이탈리아어 나레이션과 함께 등장. 2025 초.',
 array['#브레인롯', '#AI', '#미국', '#2025'],
 'new', 'brainrot', 'https://en.wikipedia.org/wiki/Italian_brainrot', null),

('Tung Tung Tung Sahur',
 array['tung tung tung sahur', '뚱뚱뚱 사후르', 'triple t'],
 '야구방망이를 든 나무토막 인간 AI 캐릭터. 인도네시아 라마단 새벽식사(사후르) 북소리에서 유래했으나 이탈리안 브레인롯으로 묶여 세계적으로 확산. 2025.',
 array['#브레인롯', '#AI', '#미국', '#2025'],
 'new', 'brainrot', 'https://knowyourmeme.com/memes/tung-tung-tung-sahur', null),

('Bombardiro Crocodilo',
 array['bombardiro crocodilo', '봄바르디로', '악어 폭격기'],
 '악어 머리에 폭격기 몸통을 단 AI 하이브리드 캐릭터. 극적인 이탈리아어 억양 나레이션과 함께 브레인롯 세계관의 빌런 격으로 등장. 2025.',
 array['#브레인롯', '#AI', '#미국', '#2025'],
 'new', 'brainrot', 'https://en.wikipedia.org/wiki/Italian_brainrot', null),

('Ballerina Cappuccina',
 array['ballerina cappuccina', '발레리나 카푸치나', '카푸치노 머리'],
 '머리가 카푸치노 잔인 발레리나 AI 캐릭터. 카푸치노 아사시노와 로맨스 라인으로 엮이는 이탈리안 브레인롯의 인기 캐릭터. 2025.',
 array['#브레인롯', '#AI', '#미국', '#2025'],
 'new', 'brainrot', 'https://en.wikipedia.org/wiki/Italian_brainrot', null),

('6-7',
 array['6-7', '식스세븐', '육칠'],
 '"6-7"이라는 숫자를 특유의 억양과 손동작으로 내뱉는 유행어 밈. 딱히 뜻은 없이 "이도저도 아닌/그저 그런"의 뉘앙스로 아이들 사이에서 폭발. 2025.',
 array['#유행어', '#GenAlpha', '#미국', '#2025'],
 'new', 'catchphrase', 'https://tinypositive.com/top-internet-memes-of-all-time/', null),

('Gurt: Yo',
 array['gurt yo', '거트 요', '요거트'],
 '"yogurt"를 쪼개 누군가 "yo, gurt"라 부르면 "gurt"가 "yo"라 답하는 말장난 밈. X에서 시작해 2025년 틱톡에서 매드마다스크 펭귄 영상과 함께 폭발.',
 array['#말장난', '#틱톡', '#미국', '#2025'],
 'new', 'catchphrase', 'https://www.tjtoday.org/41793/showcase/top-15-of-2025-internet-memes/', null),

('Adrian Explain Our Friend Group',
 array['adrian', '아드리안', '친구그룹 설명'],
 '고등학생 아드리안이 카메라 앞에서 자기 친구 그룹을 설명하며 "우린 Ohio야"라 하고, 친구가 "Swag Like Ohio"를 부르는 영상. 2025 상반기 유행.',
 array['#영상', '#틱톡', '#미국', '#2025'],
 'new', 'video', 'https://www.tjtoday.org/41793/showcase/top-15-of-2025-internet-memes/', null),

('Say You Swear',
 array['say you swear', 'say wallahi', 'AI 아기'],
 'AI로 만든 아기 얼굴을 웃음 참는 인플루언서 영상에 로토스코핑으로 입힌 밈. 충격을 표현할 때 GIF·자막으로 사용. 2025 말.',
 array['#AI', '#틱톡', '#미국', '#2025'],
 'new', 'video', 'https://www.tjtoday.org/41793/showcase/top-15-of-2025-internet-memes/', null),

('Papa Squid Game',
 array['papa squid game', '파파 오징어게임', '이병헌 아기'],
 '오징어게임 프론트맨(이병헌)이 아기가 된 456번(이정재)을 안고 있는 합성 이미지. 다들 아는 척하지만 아무도 유래를 설명 못하는 밈. 2025.',
 array['#합성', '#틱톡', '#미국', '#2025'],
 'new', 'format', 'https://www.tjtoday.org/41793/showcase/top-15-of-2025-internet-memes/', null),

('Jet2Holiday',
 array['jet2holiday', '젯투홀리데이', 'nothing beats a jet2holiday'],
 '영국 젯투 항공 광고의 밝은 "Nothing beats a Jet2Holiday!" 사운드를 여행 중 재앙 영상에 반어적으로 까는 밈. 2025 글로벌 대유행.',
 array['#사운드', '#틱톡', '#미국', '#2025'],
 'new', 'video', 'https://www.tjtoday.org/41793/showcase/top-15-of-2025-internet-memes/', null),

('Clock Strikes 12',
 array['clock strikes 12', '엘리 쇼', '오픈버스'],
 '틱토커 엘리 쇼가 영국 억양으로 즉석에서 만든 강렬한 벌스가 극적인 전달력으로 밈화. 애니메이션 템플릿으로 재사용됨. 2025 재유행.',
 array['#사운드', '#틱톡', '#미국', '#2025'],
 'new', 'video', 'https://www.tjtoday.org/41793/showcase/top-15-of-2025-internet-memes/', null),

('Dubai Chocolate',
 array['dubai chocolate', '두바이 초콜릿', '피스타치오 초콜릿'],
 '피스타치오 크림이 가득 든 두툼한 두바이산 초콜릿바를 럭셔리하게 자르는 ASMR 영상. 음식 집착과 부(富) 판타지가 만난 밈으로 브랜드 모방까지 유발. 2025.',
 array['#음식', '#틱톡', '#미국', '#2025'],
 'new', 'video', 'https://www.sheknows.com/parenting/articles/1234955404/memes-social-media-trends-2025/', null),

('Gen Z Stare',
 array['gen z stare', '젠지 스테어', '무표정 응시'],
 '점원이나 젊은 세대가 질문에 아무 반응 없이 멍하니 응시하는 "Gen Z 스테어". 무례함인지 방어기제인지 세대 논쟁을 촉발한 2025 밈.',
 array['#세대', '#틱톡', '#미국', '#2025'],
 'new', 'reaction', 'https://www.sheknows.com/parenting/articles/1234955404/memes-social-media-trends-2025/', null),

('Parker Posey White Lotus',
 array['parker posey', '파커 포지', '빅토리아 랫클리프', 'white lotus'],
 '화이트 로터스 시즌3에서 파커 포지가 연기한 감정 기복 심한 엄마 빅토리아. 그녀의 긴장된 미소와 수동공격적 대사가 온갖 상황의 반응짤로 쓰임. 2025.',
 array['#드라마', '#반응짤', '#미국', '#2025'],
 'new', 'celebrity', 'https://www.sheknows.com/parenting/articles/1234955404/memes-social-media-trends-2025/', null),

('Katy Perry Space',
 array['katy perry space', '케이티 페리 우주', '블루오리진'],
 '케이티 페리의 우주 비행 후 착륙해 땅에 입 맞추고 "내 공간을 갖겠다"고 한 장면들이 즉시 밈화. 과장된 우주 세리머니가 조롱거리가 됨. 2025.',
 array['#유명인', '#반응짤', '#미국', '#2025'],
 'new', 'celebrity', 'https://www.sheknows.com/parenting/articles/1234955404/memes-social-media-trends-2025/', null),

('Kendrick Super Bowl',
 array['kendrick lamar super bowl', '켄드릭 슈퍼볼', '슈퍼볼 하프타임'],
 '켄드릭 라마의 슈퍼볼 하프타임 공연이 밀도 높은 상징과 안무로 즉시 밈 소재가 됨. 팬들이 안무를 해석·재현하며 방송 후에도 오래 회자. 2025 초.',
 array['#음악', '#스포츠', '#미국', '#2025'],
 'new', 'celebrity', 'https://www.sheknows.com/parenting/articles/1234955404/memes-social-media-trends-2025/', null),

('Bhad Bhabie Grandma',
 array['bhad bhabie grandma', '배드바비 할머니', 'cash me ousside'],
 '"Cash me ousside"로 유명한 배드 바비(대니엘 브레골리)의 할머니가 손녀에게 당당히 맞서는 장면이 밈화. 2025.',
 array['#유명인', '#반응짤', '#미국', '#2025'],
 'new', 'celebrity', 'https://www.bu.edu/articles/2025/the-memes-that-got-us-through-2025/', null),

('Home When You Left',
 array['home when you left', '집에 있었어', '가족 나열 노래'],
 '떠날 때 집에 있던 가족을 아빠·엄마·형·누나·개·고양이·물고기까지 전부 나열하는 반복 구조의 노래 밈. 2021년 곡이 2025년 9월 역주행. 2025.',
 array['#사운드', '#틱톡', '#미국', '#2025'],
 'new', 'video', 'https://www.tjtoday.org/41793/showcase/top-15-of-2025-internet-memes/', null),

('Patrick Blank Exam',
 array['patrick star exam', '패트릭 시험지', '텅 빈 머리'],
 '스폰지밥의 패트릭 스타를 편집한 이미지로, 밤새 벼락치기 했는데 시험지를 펼치자 머릿속이 텅 빈 학생의 심정을 표현. 2025 재유행.',
 array['#반응짤', '#학생', '#미국', '#2025'],
 'new', 'reaction', 'https://www.bu.edu/articles/2025/the-memes-that-got-us-through-2025/', null),

('Nihilist Penguin',
 array['nihilist penguin', '허무주의 펭귄', '외로운 펭귄'],
 '홀로 황야를 향해 걸어가는 펭귄 사진에 실존적이거나 자조적인 문구를 붙이는 밈. 고립·불안·부조리의 감정을 표현. 2026년 1월 X에서 폭발.',
 array['#반응짤', '#감정', '#미국', '#2026'],
 'new', 'animal', 'https://www.socialchamp.com/blog/social-media-memes/', null),

-- ═══════ 2026 밈 ═══════

('Ronaldo Chocolate Milk',
 array['ronaldo chocolate milk', '호날두 초코우유', '와인잔 초코우유'],
 '호날두가 와인잔에 초코우유를 따라 마시는 이미지 밈. "2026년 첫 밈"으로 불리며 1월에 폭발적으로 퍼짐. 2026.',
 array['#유명인', '#틱톡', '#미국', '#2026'],
 'new', 'celebrity', 'https://www.tiktok.com/discover/popular-memes-of-2026', null),

('Skyrim Skeleton',
 array['skyrim skeleton', '스카이림 해골', '방패 치는 해골'],
 '게임 스카이림의 해골이 방패를 치는 짧은 장면이 밈화. 2026년 1월 인기 밈으로 부상. 2026.',
 array['#게임', '#틱톡', '#미국', '#2026'],
 'new', 'video', 'https://www.tiktok.com/discover/popular-memes-of-2026', null),

('McDonald''s CEO Burger',
 array['mcdonalds ceo burger', '맥도날드 CEO', 'CEO 햄버거'],
 '맥도날드 CEO가 신제품 버거를 먹는 영상이 밈이 되어, 다른 기업 CEO들까지 따라 먹는 릴레이로 번짐. "Peak Entertainment"로 회자. 2026년 3월.',
 array['#영상', '#틱톡', '#미국', '#2026'],
 'new', 'video', 'https://www.tiktok.com/discover/popular-memes-of-2026', null),

('Homer Dropped His Donut',
 array['homer dropped his donut', '호머 도넛', '심슨 도넛'],
 '심슨의 호머가 도넛을 떨어뜨리며 "d''oh!" 하는 장면을 노래로 만든 사운드 트렌드. 2026년 5월 유행. 2026.',
 array['#사운드', '#틱톡', '#미국', '#2026'],
 'new', 'video', 'https://www.tiktok.com/discover/popular-memes-of-2026', null),

('Stranger Things Mewing',
 array['stranger things mewing', '스트레인저 씽스 뮤잉', '일레븐 뮤잉'],
 '스트레인저 씽스 시즌5에서 일레븐의 진지한 표정을 "mewing(턱선 만들기)"에 빗대 놀리는 반응 밈. 2025년 말 시즌5 공개 후 폭발. 2025~2026.',
 array['#드라마', '#반응짤', '#미국', '#2026'],
 'new', 'reaction', 'https://www.socialchamp.com/blog/social-media-memes/', null),

('Bad Bunny Super Bowl',
 array['bad bunny super bowl', '배드버니 슈퍼볼', '슈퍼볼 LX'],
 '배드 버니의 슈퍼볼 LX 하프타임 공연의 격정적인 무대가 즉시 밈화. 라이브 이벤트의 카오스한 에너지를 표현. 2026년 2월.',
 array['#음악', '#스포츠', '#미국', '#2026'],
 'new', 'celebrity', 'https://www.socialchamp.com/blog/social-media-memes/', null),

('It''s Over 9000',
 array['over 9000', '9000 이상', '드래곤볼 베지터'],
 '드래곤볼Z에서 베지터가 전투력 측정기를 부수며 "It''s over 9000!"이라 외치는 장면. 엄청난 수치를 과장할 때 쓰는 고전 밈. 2000년대 후반.',
 array['#고전', '#애니', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://www.thetoptens.com/memes/greatest-internet-memes/', null),

('Harambe',
 array['harambe', '하람베', '고릴라 하람베'],
 '2016년 신시내티 동물원에서 사살된 고릴라 하람베. "dicks out for Harambe" 등 추모를 빙자한 부조리 유머로 오래 회자된 밈.',
 array['#고전', '#동물', '#미국', '#스테디'],
 'new', 'animal', 'https://podcavern.com/186-top-5-all-time-classic-memes/', null),

('Press F to Pay Respects',
 array['press f', '경의를 표하려면 F', 'pay respects'],
 '게임 콜 오브 듀티에서 "F를 눌러 경의를 표하라"는 QTE가 밈이 됨. 무언가 안타깝게 끝났을 때 채팅에 "F"를 치는 관습으로 정착. 2014.',
 array['#고전', '#게임', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://podcavern.com/186-top-5-all-time-classic-memes/', null),

('Karen',
 array['karen', '카렌', '진상 손님'],
 '"매니저 불러와" 식으로 갑질하는 중년 여성을 통칭하는 밈적 캐릭터. 무리한 요구를 하는 진상을 가리키는 대명사로 정착. 2010년대 후반.',
 array['#고전', '#캐릭터', '#미국', '#스테디'],
 'new', 'character', 'https://podcavern.com/186-top-5-all-time-classic-memes/', null),

('Ancient Aliens Guy',
 array['ancient aliens', '고대 외계인', '지오르지오'],
 '방송인 지오르지오 추칼로스가 머리를 흩날리며 "외계인 때문(aliens)"이라 단정 짓는 장면. 설명 안 되는 걸 억지로 갖다 붙일 때 쓰는 밈. 2010.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Y U NO',
 array['y u no', '와이 유 노', '와이유노 가이'],
 '단순한 얼굴 그림에 "Y U NO (do X)?!"라고 외치는 초기 랄로 밈. 답답한 상황에서 항의할 때 씀. 2010.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.meme-hall-of-fame.com/', null),

('Futurama Fry',
 array['futurama fry', '퓨처라마 프라이', 'not sure if'],
 '퓨처라마의 프라이가 눈을 가늘게 뜨고 "Not sure if X or Y"라 의심하는 장면. 애매한 상황을 저울질할 때 쓰는 템플릿. 2011.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://www.meme-hall-of-fame.com/', null),

('I Can Has Cheezburger',
 array['i can has cheezburger', '치즈버거 고양이', 'lolcat'],
 '통통한 고양이 사진에 엉터리 철자 캡션 "I Can Has Cheezburger?"를 붙인 롤캣(lolcat)의 상징. 초기 인터넷 밈 문화의 뿌리. 2007.',
 array['#고전', '#동물', '#미국', '#스테디'],
 'new', 'animal', 'https://www.meme-hall-of-fame.com/', null),

('Rage Comics',
 array['rage comics', '레이지 코믹', 'fffuuu'],
 '조악한 손그림 얼굴(Rage Guy, Trollface 등)로 일상의 짜증나는 순간을 4컷으로 그린 만화 포맷. 2008~2012 인터넷을 지배. 2008.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://www.meme-hall-of-fame.com/', null),

('The Game',
 array['the game', '더 게임', '생각하면 짐'],
 '"The Game을 생각하는 순간 The Game에서 진다"는 규칙의 무한 밈. 이 문장을 읽은 당신은 방금 졌다. 2000년대.',
 array['#고전', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://podcavern.com/186-top-5-all-time-classic-memes/', null),

('Chloe Side Eye',
 array['chloe side eye', '클로이 곁눈질', '디즈니랜드 클로이'],
 '디즈니랜드 깜짝 발표에 언니는 울고, 옆의 동생 클로이는 카메라를 향해 어리둥절하게 곁눈질하는 장면. 미묘한 반응을 표현하는 반응짤. 2013.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://www.tiktok.com/discover/most-popular-memes', null),

('Keyboard Cat',
 array['keyboard cat', '키보드 고양이', '연주하는 고양이'],
 '옷을 입은 고양이가 키보드를 연주하는 듯한 영상. 실수나 망한 순간 뒤에 "Play him off, Keyboard Cat"으로 붙이는 고전 영상 밈. 2007.',
 array['#고전', '#동물', '#미국', '#스테디'],
 'new', 'animal', 'https://www.tiktok.com/discover/most-popular-memes', null),

('Salt Bae',
 array['salt bae', '소금 뿌리는 남자', '누스렛'],
 '셰프 누스렛이 팔꿈치를 타고 소금을 흩뿌리는 특유의 포즈. 무언가를 폼나게 마무리할 때 쓰는 포즈 밈. 2017.',
 array['#고전', '#유명인', '#미국', '#스테디'],
 'new', 'celebrity', 'https://knowyourmeme.com/', null),

('Crying Jordan',
 array['crying jordan', '우는 조던', '마이클 조던 눈물'],
 '명예의 전당 연설 중 눈물 흘리는 마이클 조던의 얼굴을 패자·실패자에게 합성하는 밈. 스포츠 SNS의 오랜 놀림용 짤. 2016.',
 array['#고전', '#스포츠', '#미국', '#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Arthur Fist',
 array['arthur fist', '아서 주먹', '꽉 쥔 주먹'],
 '만화 아서가 주먹을 꽉 쥔 손 클로즈업. 참으려 애쓰는 분노를 표현하는 반응짤. 2016.',
 array['#고전', '#반응짤', '#미국', '#스테디'],
 'new', 'reaction', 'https://knowyourmeme.com/', null),

('Tuxedo Winnie the Pooh',
 array['tuxedo pooh', '턱시도 곰돌이 푸', '고급 푸'],
 '평범한 푸와 턱시도 입은 우아한 푸를 위아래로 붙여, 같은 것을 "격 있게" 다시 말하는 2단 밈. 2019.',
 array['#고전', '#포맷', '#미국', '#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Bernie Mittens',
 array['bernie mittens', '버니 샌더스 벙어리장갑', '접이식 의자 버니'],
 '2021년 미국 취임식에서 버니 샌더스가 벙어리장갑을 끼고 접이식 의자에 팔짱 낀 채 앉은 사진. 온갖 배경에 합성되며 폭발. 2021.',
 array['#고전', '#합성', '#미국', '#스테디'],
 'new', 'celebrity', 'https://knowyourmeme.com/', null),

('Grimace Shake',
 array['grimace shake', '그리메이스 셰이크', '보라돌이 셰이크'],
 '맥도날드 그리메이스 생일 보라색 셰이크를 마신 뒤 죽은 척 쓰러지는 호러 패러디 영상 트렌드. 2023 여름 폭발. 2023.',
 array['#고전', '#영상', '#미국', '#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),

('Girl Dinner',
 array['girl dinner', '걸 디너', '대충 저녁'],
 '치즈·크래커·올리브처럼 조리 없이 대충 집어먹는 한 끼를 "girl dinner"라 부르는 밈. 2023.',
 array['#고전', '#음식', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Barbenheimer',
 array['barbenheimer', '바벤하이머', '바비 오펜하이머'],
 '2023년 같은 날 개봉한 정반대 톤의 영화 바비와 오펜하이머를 한데 묶어 즐긴 밈. 핑크빛 코미디와 핵폭탄 드라마의 기묘한 조합. 2023.',
 array['#고전', '#영화', '#미국', '#스테디'],
 'new', 'format', 'https://knowyourmeme.com/', null),

('Ohio',
 array['ohio', '오하이오', 'only in ohio'],
 '"오직 오하이오에서만(only in Ohio)" 온갖 괴상한 일이 벌어진다는 부조리 밈. Gen Alpha 슬랭에서 "이상한 곳"의 대명사로 쓰임. 2010년대 말~.',
 array['#고전', '#GenAlpha', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Gyatt',
 array['gyatt', '갓', '갸트'],
 '"God damn"에서 파생된 Gen Alpha 감탄사. 놀람이나 감탄을 과장되게 표현할 때 쓰며 skibidi·rizz와 함께 묶임. 2023.',
 array['#고전', '#GenAlpha', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://www.nbcnews.com/pop-culture/best-memes-moments-2024-brat-demure-hawk-tuah-rcna181956', null),

('Fanum Tax',
 array['fanum tax', '파넘 택스', '음식 세금'],
 '스트리머 Fanum이 친구 음식을 한 입씩 뺏어 먹는 데서 온 "Fanum tax". 남의 것을 슬쩍 가져가는 행위를 뜻하는 Gen Alpha 슬랭. 2023.',
 array['#고전', '#GenAlpha', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Mewing',
 array['mewing', '뮤잉', '턱선 만들기'],
 '혀를 입천장에 붙여 턱선을 살린다는 "mewing"이 밈화. 말하기 싫을 때 턱을 쓸며 조용히 하라는 제스처로도 쓰임. 2023~2024.',
 array['#고전', '#GenAlpha', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Chill Guy',
 array['chill guy', '칠 가이', '느긋한 개'],
 '후드티에 바지를 입고 무심하게 서 있는 개 캐릭터 "my honest reaction / just a chill guy". 무슨 일이 있어도 태연한 태도를 표현. 2024.',
 array['#고전', '#캐릭터', '#미국', '#스테디'],
 'new', 'character', 'https://knowyourmeme.com/', null),

('Just Put the Fries in the Bag',
 array['fries in the bag', '감자튀김 봉지에', '변명 그만'],
 '변명 늘어놓는 상대에게 "됐고 감자튀김이나 봉지에 넣어(just put the fries in the bag bro)"라고 쏘아붙이는 유행어. 2024.',
 array['#고전', '#유행어', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('Delulu',
 array['delulu', '델룰루', '망상'],
 '"delusional"을 귀엽게 줄인 "delulu". 근거 없는 낙관이나 망상적 기대를 자조적으로 표현하는 유행어. 2023~2024.',
 array['#고전', '#유행어', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://knowyourmeme.com/', null),

('It''s Corn',
 array['its corn', '옥수수 소년', 'corn kid'],
 '한 소년이 옥수수를 예찬하는 인터뷰가 노래로 리믹스된 "It''s Corn" 밈. 순수한 기쁨의 상징으로 널리 퍼짐. 2022.',
 array['#고전', '#영상', '#미국', '#스테디'],
 'new', 'video', 'https://knowyourmeme.com/', null),
('Rizz',
 array['rizz', '리즈', '카리스마 매력'],
 '"charisma"에서 온 슬랭 "rizz(이성을 끄는 매력)". 2023년 옥스퍼드 올해의 단어로 뽑히며 Gen Z 필수 유행어로 정착. 이후 "rizzler", "unspoken rizz" 등 파생. 2023.',
 array['#고전', '#유행어', '#미국', '#스테디'],
 'new', 'catchphrase', 'https://www.nbcnews.com/pop-culture/best-memes-moments-2024-brat-demure-hawk-tuah-rcna181956', null)
on conflict (name) do nothing;
