-- 바꾼 5개 덱 + 신규 덱 4개(lukewarm-flat, half-broken, wasted-timing, body-device) 코드→DB 반영 (2026-07-13).
-- 기존 5개는 sort/is_public 안 건드림. 신규 덱은 맨 뒤로(sort=max+1) 삽입되며, 순서는 대시보드에서 조정 가능.
-- Supabase 대시보드 > SQL Editor 에 붙여넣고 Run.

-- [선택] 실행 전 현재 5개 덱 백업(결과를 따로 저장해두면 롤백 가능):
--   select id, title, data from decks where id in ('dirty-partner', 'gross-food', 'kakao', 'salty-bland', 'tomato-vomit');

-- dirty-partner
insert into decks (id, title, emoji, data, is_public, updated_at)
values ('dirty-partner', '평생 함께라면? 털털이 vs 결벽러', '🧼', '{"id":"dirty-partner","title":"평생 함께라면? 털털이 vs 결벽러","icon":"🧼","type":"person","a":{"name":"털털이","emoji":"💨","penalties":[{"strength":2,"text":"뭘 흘리고 묻혀도 태연해 남들이 지저분하다 여김","short":"묻혀도 태연"},{"strength":3,"text":"방이 늘 어질러져 필요한 걸 매번 못 찾음","short":"물건 자주 실종"},{"strength":4,"text":"유통기한 지난 음식도 무심코 먹어 종종 배탈이 남","short":"유통기한 배탈"},{"strength":5,"text":"옷 얼룩에 무신경해 소개팅에서 감점","short":"얼룩에 소개팅 감점"},{"strength":6,"text":"청소를 미루다 결국 몰아서 대청소 지옥을 겪음","short":"몰아치는 대청소"},{"strength":7,"text":"위생 관념이 다른 연인과 매번 부딪힘","short":"위생차로 연인 충돌"},{"strength":8,"text":"냄새에 둔감해 남이 말해줘야 알아차림","short":"냄새 둔감"},{"strength":9,"text":"손을 잘 안 씻어 감기·배탈을 달고 삶","short":"손 안 씻어 잔병"},{"strength":10,"text":"''게으르다''는 오해를 평생 받음","short":"게으름 오해 평생"}]},"b":{"name":"결벽러","emoji":"🧴","penalties":[{"strength":2,"text":"조금만 지저분해도 참지 못해 늘 예민해짐","short":"티끌에도 예민"},{"strength":3,"text":"남이 만진 물건·손잡이를 못 만져 생활이 불편함","short":"손잡이 공포"},{"strength":4,"text":"청소·소독에 매일 몇 시간과 돈을 쏟아부음","short":"매일 청소에 탕진"},{"strength":5,"text":"대중교통·공용 화장실을 쓸 때마다 스트레스를 받음","short":"공용시설 스트레스"},{"strength":6,"text":"여행을 가도 숙소 위생 때문에 잠을 설침","short":"숙소 위생에 뜬눈"},{"strength":7,"text":"친구가 집에 놀러 오는 게 반갑지 않음","short":"손님 오면 부담"},{"strength":8,"text":"손을 너무 자주 씻어 피부가 트고 갈라짐","short":"손 트고 갈라짐"},{"strength":9,"text":"연인의 사소한 습관 하나에도 예민하게 굴게 됨","short":"사소한 습관에 발끈"},{"strength":10,"text":"''유난 떤다''는 소리를 평생 들음","short":"유난 소리 평생"}]},"resultCards":{"a":{"extreme":{"label":"편한 게 최고라 끝까지 눈감은 털털이파"},"mild":{"label":"편한 건 좋은데 위생은 걸려 저울질하는 털털이파"}},"b":{"extreme":{"label":"먼지 한 톨까지 잡고 사는 결벽러파"},"mild":{"label":"깔끔한 건 좋은데 가끔 숨 막히는 결벽러파"}}}}'::jsonb, true, now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;

-- gross-food
insert into decks (id, title, emoji, data, is_public, updated_at)
values ('gross-food', '평생 이것만: 똥맛 카레 vs 카레맛 똥', '🍛', '{"id":"gross-food","title":"평생 이것만: 똥맛 카레 vs 카레맛 똥","icon":"🍛","type":"attribute","penaltyStyleOverride":"long","a":{"name":"똥맛 카레","emoji":"💩","penalties":[{"strength":2,"text":"겉은 멀쩡한 카레인데 입에 넣으면 그 맛이 확 퍼짐","short":"겉만 멀쩡한 카레"},{"strength":3,"text":"하루 한 끼는 무조건 이걸로 먹어야 함","short":"하루 한 끼 강제"},{"strength":4,"text":"남들 앞에서 아무렇지 않게 맛있는 척 먹어야 함","short":"맛있는 척 연기"},{"strength":5,"text":"평생 다른 카레는 못 먹음","short":"다른 카레 금지"},{"strength":6,"text":"먹고 나면 그 맛이 하루 종일 입에 맴돎","short":"종일 입에 그 맛"},{"strength":7,"text":"냄새는 정상 카레라 남들은 맛있는 줄 앎","short":"남들은 정상인 줄"},{"strength":8,"text":"다 먹어도 배는 안 부름","short":"먹어도 배 안 참"},{"strength":9,"text":"소개팅 첫 메뉴가 이걸로 정해짐","short":"소개팅 첫 메뉴"},{"strength":10,"text":"리필은 무제한인데 남기면 벌칙이 있음","short":"남기면 벌칙"}]},"b":{"name":"카레맛 똥","emoji":"🍛","penalties":[{"strength":2,"text":"겉모습·냄새는 진짜 그것인데 맛만 카레임","short":"정체는 그것"},{"strength":3,"text":"하루 한 끼는 무조건 이걸로 먹어야 함","short":"하루 한 끼 강제"},{"strength":4,"text":"남이 보면 대체 뭘 먹나 경악함","short":"보면 다들 경악"},{"strength":5,"text":"맛은 괜찮은데 먹는 내 표정 관리가 안 됨","short":"표정 관리 실패"},{"strength":6,"text":"가족과 겸상하며 같이 먹어야 함","short":"가족과 겸상"},{"strength":7,"text":"다 먹어도 배는 안 부름","short":"먹어도 배 안 참"},{"strength":8,"text":"손·그릇에 묻으면 씻어도 찝찝함이 남음","short":"묻으면 영 찝찝"},{"strength":9,"text":"리필은 공짜인데 남기면 두 개로 늘어남","short":"남기면 두 개로"},{"strength":10,"text":"맛있다고 인정하는 순간 자괴감이 몰려옴","short":"맛 인정=자괴감"}]},"resultCards":{"a":{"extreme":{"label":"맛은 지옥이어도 몸은 챙긴 똥맛 카레파"},"mild":{"label":"냄새는 힘든데 그래도 진짜 음식이라 참는 똥맛 카레파"}},"b":{"extreme":{"label":"정체를 알면서도 맛에 굴복한 카레맛 똥파"},"mild":{"label":"맛은 좋은데 정체가 자꾸 걸리는 카레맛 똥파"}}}}'::jsonb, true, now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;

-- kakao
insert into decks (id, title, emoji, data, is_public, updated_at)
values ('kakao', '카톡 3초컷 애인 vs 카톡 3일컷 애인', '💬', '{"id":"kakao","title":"카톡 3초컷 애인 vs 카톡 3일컷 애인","icon":"💬","type":"person","a":{"name":"집착러","emoji":"📲","penalties":[{"strength":2,"text":"답장이 1분만 늦어도 무슨 일 있냐고 다그침","short":"1분 늦으면 추궁"},{"strength":3,"text":"하루에도 수십 번 실시간 보고를 요구함","short":"실시간 보고 요구"},{"strength":4,"text":"내 위치·일정을 늘 확인하려 함","short":"위치·일정 감시"},{"strength":5,"text":"친구들과 있을 때도 계속 연락이 옴","short":"모임에도 연락 폭탄"},{"strength":6,"text":"답장 속도로 애정을 가늠해 부담스러움","short":"답장속도=애정"},{"strength":7,"text":"싸우면 그 집착이 두 배가 됨","short":"싸우면 집착 폭증"},{"strength":8,"text":"답장만 빼면 완벽한 사람이라 헤어지긴 아까움","short":"답장 빼면 완벽"},{"strength":9,"text":"혼자만의 시간을 갖기가 어려움","short":"혼자 시간 실종"},{"strength":10,"text":"이 패턴이 사귀는 내내 안 바뀜","short":"평생 그대로"}]},"b":{"name":"잠수함","emoji":"🌊","penalties":[{"strength":2,"text":"답장이 며칠씩 늦어 늘 애가 탐","short":"며칠째 무응답"},{"strength":3,"text":"중요한 날에도 연락이 뜸함","short":"중요한 날도 잠수"},{"strength":4,"text":"살아 있나 걱정될 만큼 잠수를 탐","short":"생사 확인 불가"},{"strength":5,"text":"내가 매달리는 모양새가 되어 자존심이 상함","short":"나만 매달리는 꼴"},{"strength":6,"text":"데이트 약속을 잡기까지 며칠이 걸림","short":"약속잡기 며칠"},{"strength":7,"text":"애정이 식은 건지 헷갈려 늘 불안함","short":"식었나 늘 불안"},{"strength":8,"text":"답장만 빼면 완벽한 사람이라 헤어지긴 아까움","short":"답장 빼면 완벽"},{"strength":9,"text":"장거리라 연락이 유일한 소통인데도 그럼","short":"장거리에도 잠수"},{"strength":10,"text":"이 패턴이 사귀는 내내 안 바뀜","short":"평생 그대로"}]},"resultCards":{"a":{"extreme":{"label":"24시간 감시받아도 사랑이면 됐다는 집착러파"},"mild":{"label":"관심은 좋은데 숨은 좀 쉬고 싶은 집착러파"}},"b":{"extreme":{"label":"혼자가 편하면 각방도 좋다는 잠수함파"},"mild":{"label":"자유는 좋은데 가끔 서운한 잠수함파"}}}}'::jsonb, true, now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;

-- salty-bland
insert into decks (id, title, emoji, data, is_public, updated_at)
values ('salty-bland', '모든 음식이 다 짬 vs 모든 음식이 다 밍밍함', '🧂', '{"id":"salty-bland","title":"모든 음식이 다 짬 vs 모든 음식이 다 밍밍함","icon":"🧂","type":"attribute","penaltyStyleOverride":"long","a":{"name":"짠맛지옥","emoji":"🧂","penalties":[{"strength":2,"text":"모든 음식이 소금 덩어리처럼 짜게 느껴짐","short":"다 소금 덩어리"},{"strength":3,"text":"물조차 짜게 느껴져 갈증이 안 가심","short":"물조차 짜서 갈증"},{"strength":4,"text":"디저트·과일도 예외 없이 짬","short":"디저트도 다 짬"},{"strength":5,"text":"남들은 정상으로 먹는 걸 옆에서 지켜봐야 함","short":"남들 정상식 구경"},{"strength":6,"text":"직접 싱겁게 요리해도 결과는 똑같이 짬","short":"싱겁게 해도 짬"},{"strength":7,"text":"자꾸 물을 마셔 늘 붓고 속이 더부룩함","short":"붓고 더부룩"},{"strength":8,"text":"미슐랭 음식도 똑같이 짬","short":"미슐랭도 짬"},{"strength":9,"text":"먹는 자리가 유독 많은 삶임","short":"밥자리마다 고역"},{"strength":10,"text":"평생 그 상태가 안 바뀜","short":"평생 그대로"}]},"b":{"name":"무맛지옥","emoji":"🥣","penalties":[{"strength":2,"text":"모든 음식이 물 씹는 것처럼 아무 맛도 없음","short":"다 물 씹는 맛"},{"strength":3,"text":"아무리 먹어도 만족감이 없어 자꾸 더 먹게 됨","short":"만족 없어 과식"},{"strength":4,"text":"매운 것·단 것 같은 자극도 하나도 안 느껴짐","short":"매운·단맛도 0"},{"strength":5,"text":"좋아하던 음식조차 먹을 이유가 사라짐","short":"먹을 이유 상실"},{"strength":6,"text":"남들이 ''맛있다''며 행복해하는 걸 이해 못 함","short":"남들 행복 미스터리"},{"strength":7,"text":"먹는 즐거움이 없어 끼니가 노동이 됨","short":"끼니가 노동"},{"strength":8,"text":"미슐랭 음식도 똑같이 무맛임","short":"미슐랭도 무맛"},{"strength":9,"text":"맛 표현을 못 해 대화에서 겉돎","short":"맛 얘기서 겉돎"},{"strength":10,"text":"평생 그 상태가 안 바뀜","short":"평생 그대로"}]},"resultCards":{"a":{"extreme":{"label":"흰쌀밥 없인 물도 못 넘기는 짠맛지옥러"},"mild":{"label":"남몰래 소금 뿌리다 걸리는 짠맛러"}},"b":{"extreme":{"label":"캡사이신 없인 물도 맹맹한 무맛지옥러"},"mild":{"label":"남몰래 청양고추 까 넣는 무맛러"}}}}'::jsonb, true, now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;

-- tomato-vomit
insert into decks (id, title, emoji, data, is_public, updated_at)
values ('tomato-vomit', '평생 이것만: 토맛 토마토 vs 토마토맛 토', '🍅', '{"id":"tomato-vomit","title":"평생 이것만: 토맛 토마토 vs 토마토맛 토","icon":"🍅","type":"attribute","penaltyStyleOverride":"long","a":{"name":"토맛 토마토","emoji":"🍅","penalties":[{"strength":2,"text":"겉은 싱싱한 토마토인데 씹으면 그 맛이 확 퍼짐","short":"겉만 싱싱 토마토"},{"strength":3,"text":"하루 한 개는 무조건 먹어야 함","short":"하루 한 개 강제"},{"strength":4,"text":"남들 앞에서 아무렇지 않게 먹어야 함","short":"태연한 척 먹기"},{"strength":5,"text":"평생 다른 토마토 요리는 못 먹음","short":"토마토요리 금지"},{"strength":6,"text":"먹고 나면 그 맛이 30분간 입에 맴돎","short":"30분 입에 그 맛"},{"strength":7,"text":"케첩·파스타 등 토마토 든 음식도 다 그 맛임","short":"케첩·파스타도 그 맛"},{"strength":8,"text":"눈을 감고 먹어도 뇌는 정체를 앎","short":"눈 감아도 뇌는 앎"},{"strength":9,"text":"냄새는 정상 토마토라 남들은 멀쩡한 줄 앎","short":"남들은 정상인 줄"},{"strength":10,"text":"리필은 공짜인데 남기면 두 개로 늘어남","short":"남기면 두 개로"}]},"b":{"name":"토마토맛 토","emoji":"🤮","penalties":[{"strength":2,"text":"겉모습·냄새는 진짜 그것인데 맛만 토마토임","short":"정체는 그것"},{"strength":3,"text":"하루 한 개는 무조건 먹어야 함","short":"하루 한 개 강제"},{"strength":4,"text":"남이 보면 대체 뭘 먹나 경악함","short":"보면 다들 경악"},{"strength":5,"text":"맛은 괜찮은데 먹는 내 표정 관리가 안 됨","short":"표정 관리 실패"},{"strength":6,"text":"정체를 아는 순간 뇌가 계속 거부함","short":"뇌가 계속 거부"},{"strength":7,"text":"소개팅·가족 식사 자리에서 먹게 됨","short":"소개팅서도 강제"},{"strength":8,"text":"손·그릇에 묻으면 씻어도 찝찝함이 남음","short":"묻으면 영 찝찝"},{"strength":9,"text":"리필은 공짜인데 남기면 두 개로 늘어남","short":"남기면 두 개로"},{"strength":10,"text":"맛있다고 인정하는 순간 자괴감이 몰려옴","short":"맛 인정=자괴감"}]},"resultCards":{"a":{"extreme":{"label":"온 동네에 ''토마토 그 사람''으로 박제된 토맛 토마토파"},"mild":{"label":"유명해지긴 했는데 발 뺄까 고민하는 토맛 토마토파"}},"b":{"extreme":{"label":"세상이 등 돌려도 그 맛에 대물림까지 간 토마토맛 토파"},"mild":{"label":"맛엔 넘어갔는데 사람들 시선이 자꾸 걸리는 토마토맛 토파"}}}}'::jsonb, true, now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;


-- lukewarm-flat (신규 덱 · v3 온-테마 · 2026-07-13)
insert into decks (id, title, emoji, data, is_public, sort, updated_at)
values ('lukewarm-flat', '미지근국 vs 김빠진 음료', '🥣', '{"id":"lukewarm-flat","title":"미지근국 vs 김빠진 음료","icon":"🥣","type":"attribute","a":{"name":"미지근국","emoji":"🍲","penalties":[{"strength":2,"text":"갓 지은 밥도 내 앞에선 늘 한 김 식어 미적지근함","merit":"뜨거운 밥에 입천장 델 일이 없음"},{"strength":3,"text":"아이스크림이 늘 반쯤 녹은 채로만 넘어옴","merit":"찬 걸 급히 먹어도 머리가 띵해질 일이 없음"},{"strength":4,"text":"갓 나온 국·찌개가 내 앞에만 오면 미지근해짐","merit":"뜨거운 뚝배기·국그릇에 손 델 걱정이 없음"},{"strength":5,"text":"시원한 물을 벌컥벌컥 마셔도 늘 미적지근하게 느껴짐","merit":"찬물에 이가 시려 인상 쓸 일이 없음"},{"strength":6,"text":"갓 뽑은 커피가 늘 뜨겁지도 차갑지도 않은 애매한 온도임","merit":"뜨거워서 식을 때까지 후후 불며 기다릴 일이 없음"},{"strength":7,"text":"라면이 늘 한 김 죽어 살짝 불은 채로 완성됨","merit":"급하게 먹어도 뜨거워 데거나 못 먹을 일이 없음"},{"strength":8,"text":"겨울에 호호 불며 먹는 붕어빵·어묵 국물의 그 뜨끈함을 못 느낌","merit":"한여름에도 뜨거운 음식이 부담스러울 일이 없음"},{"strength":9,"text":"미슐랭·오마카세를 가도 갓 낸 요리가 내 입엔 늘 미지근하게 닿음","merit":"너무 뜨겁거나 차가워 첫입에 맛을 놓치는 법이 없음"},{"strength":10,"text":"평생 뜨끈한 국물 한 술, 살얼음 낀 냉면 한 젓가락의 온도를 못 느끼고 삶","merit":"평생 혀 데고 배탈 나는 온도 사고 없이 늘 순하게 먹음"}]},"b":{"name":"김빠진 음료","emoji":"🥤","penalties":[{"strength":2,"text":"갓 딴 콜라도 내 입엔 늘 김 빠진 맹맹한 맛으로만 느껴짐","merit":"탄산이 코·목을 쏘아 사레들 일이 없음"},{"strength":3,"text":"맥주 첫 잔의 그 짜릿한 목 넘김을 평생 못 느낌","merit":"트림이 콱 올라와 민망할 일이 없음"},{"strength":4,"text":"사이다를 흔들어 따도 거품 한 번 안 올라오고 밍밍함","merit":"흔들린 탄산이 터져 옷·손에 튈 일이 없음"},{"strength":5,"text":"톡 쏘는 맛에 마시는 하이볼·스파클링이 다 맹물처럼 느껴짐","merit":"탄산에 배가 빵빵하게 부풀 일이 없음"},{"strength":6,"text":"갓 개봉한 탄산수도 나에게만 김 다 빠진 맹탕임","merit":"김 빠질까 급하게 들이켜야 하는 조급함이 없음"},{"strength":7,"text":"회식·파티에서 다들 짜릿하다는 그 맛을 나만 못 느껴 겉돎","merit":"탄산이 위를 자극해 속 쓰릴 일이 없음"},{"strength":8,"text":"콜라·맥주·사이다 뭘 시켜도 결국 다 같은 맹맹한 맛임","merit":"자기 전 마셔도 속 더부룩해 잠 설칠 일이 없음"},{"strength":9,"text":"유명 수제 맥주·샴페인을 따도 그 톡 쏘는 값을 나만 못 누림","merit":"탄산에 이 삭고 살찐다는 걱정에서 자유로움"},{"strength":10,"text":"평생 캬 하고 터지는 그 짜릿한 한 모금을 못 느끼고 밍밍하게 삶","merit":"평생 탄산 과음으로 속 버리거나 이 상할 일 없이 지냄"}]},"resultCards":{"a":{"extreme":{"label":"혀 델 걱정 없는 미적지근이 평화라는 미지근국파"},"mild":{"label":"뜨끈한 국물은 그리운데 데는 것보단 낫다는 미지근국파"}},"b":{"extreme":{"label":"짜릿함 없어도 속 편한 맹탕이 최고라는 김빠진음료파"},"mild":{"label":"톡 쏘는 맛은 아쉬운데 속은 안 버려 다행인 김빠진음료파"}}}}'::jsonb, true, (select coalesce(max(sort),0)+1 from decks), now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;
-- half-broken (신규 덱 · v3 온-테마 · 2026-07-13)
insert into decks (id, title, emoji, data, is_public, sort, updated_at)
values ('half-broken', '한쪽 코막힘 vs 한쪽 이어폰 소리 작음', '🔧', '{"id":"half-broken","title":"한쪽 코막힘 vs 한쪽 이어폰 소리 작음","icon":"🔧","type":"attribute","a":{"name":"한쪽 코막힘","emoji":"👃","penalties":[{"strength":2,"text":"평생 한쪽 콧구멍만 살짝 막혀 숨 쉴 때 미묘하게 답답함","merit":"완전히 코 막히거나 가래가 껴도 몇 초 만에 뻥 뚫림"},{"strength":3,"text":"재채기가 나올 듯 잔뜩 인상 썼다가 코끝에서 쏙 들어가 찝찝함","merit":"남들 앞에서 크게 재채기해 민망할 일이 없음"},{"strength":4,"text":"한쪽으로만 코가 막혀 잘 때 늘 그 반대로 돌아누워야 함","merit":"어떤 베개·자세로 자도 목·어깨가 안 결림"},{"strength":5,"text":"환절기엔 막힌 쪽 코가 더 답답해져 온종일 킁킁댐","merit":"환절기에도 감기·몸살로 앓아누울 일이 없음"},{"strength":6,"text":"매운 것·뜨거운 걸 먹으면 한쪽 코에서만 콧물이 주르륵 남","merit":"매운 걸 아무리 먹어도 다음 날 속이 안 쓰림"},{"strength":7,"text":"냄새를 맡을 때 한쪽이 둔해 향을 늘 반쪽만 느낌","merit":"상한 음식 냄새만은 귀신같이 먼저 알아차림"},{"strength":8,"text":"자고 일어나면 막힌 쪽이 좌우로 바뀌어 있어 종잡을 수 없음","merit":"자고 일어나면 늘 몸이 개운하고 안 뻐근함"},{"strength":9,"text":"중요한 자리에서 킁킁대는 걸 참느라 신경이 온통 코에 쏠림","merit":"긴장되는 자리에서도 손발에 땀이 안 나고 안 떨림"},{"strength":10,"text":"평생 양쪽 코로 시원하게 숨 한번 크게 못 쉬고 삶","merit":"평생 큰 병치레 없이 잔병 하나 없는 몸으로 삶"}]},"b":{"name":"한쪽 이어폰","emoji":"🎧","penalties":[{"strength":2,"text":"평생 한쪽 이어폰만 소리가 미묘하게 작아 늘 좌우 균형이 안 맞음","merit":"아무리 시끄러운 곳에서도 듣고 싶은 소리만 골라 들림"},{"strength":3,"text":"귓가에 앵앵대는 모기 소리에 불을 켜면 귀신같이 사라져 헛심만 씀","merit":"어떤 소음 속에서도 나는 늘 푹 잘 잠"},{"strength":4,"text":"바쁘게 움직이면 이어폰 줄이 문고리·주머니에 걸려 홱 빠짐","merit":"이어폰 줄이 엉키거나 한 짝을 잃어버릴 일이 없음"},{"strength":5,"text":"노래를 들으면 좌우 밸런스가 안 맞아 한쪽으로만 쏠려 들림","merit":"어떤 음악도 나에겐 늘 최고의 음질로 들림"},{"strength":6,"text":"통화할 때 상대 목소리가 한쪽 귀에서만 작게 들려 자꾸 되물음","merit":"시끄러운 카페에서도 상대 목소리만 또렷하게 들림"},{"strength":7,"text":"조용한 방에선 약한 쪽 귀가 먹먹한 느낌이 들어 신경 쓰임","merit":"귀에 물이 들어가도 몇 초 만에 저절로 빠져 개운함"},{"strength":8,"text":"영화·게임의 방향 소리를 반쪽만 느껴 늘 몰입이 깨짐","merit":"이어폰·헤드폰을 오래 껴도 귀가 안 아프고 안 먹먹함"},{"strength":9,"text":"볼륨을 아무리 맞춰도 한쪽만 크게 느껴져 늘 애매함","merit":"주변이 시끄러워도 집중할 땐 소음이 저절로 배경으로 사라짐"},{"strength":10,"text":"평생 양쪽으로 꽉 찬 소리의 그 균형을 못 느끼고 삶","merit":"평생 이명·난청 없이 늘 또렷하게 잘 들으며 삶"}]},"resultCards":{"a":{"extreme":{"label":"한쪽 킁킁대도 큰 병 없는 게 남는 장사라는 반쪽코파"},"mild":{"label":"숨은 좀 답답한데 잔병 없어 버티는 반쪽코파"}},"b":{"extreme":{"label":"한쪽 작아도 듣고 싶은 것만 골라 듣는 반쪽귀파"},"mild":{"label":"밸런스는 아쉬운데 귀는 편해 다행인 반쪽귀파"}}}}'::jsonb, true, (select coalesce(max(sort),0)+1 from decks), now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;
-- wasted-timing (신규 덱 · v3 일상현타 · 2026-07-13)
insert into decks (id, title, emoji, data, is_public, sort, updated_at)
values ('wasted-timing', '매번 헛수고 vs 매번 한 끗 차이', '😩', '{"id":"wasted-timing","title":"매번 헛수고 vs 매번 한 끗 차이","icon":"😩","type":"attribute","a":{"name":"헛수고 현타","emoji":"🔁","penalties":[{"strength":2,"text":"한 장만 뽑으려는데 곽티슈가 뭉텅이로 딸려 나와 도로 욱여넣음","merit":"정작 급할 때 휴지가 늘 손 닿는 곳에 있음"},{"strength":3,"text":"안경 깨끗이 닦자마자 렌즈 한가운데 내 지문을 다시 묻힘","merit":"안경·화면이 웬만해선 잘 안 더러워짐"},{"strength":4,"text":"얼음틀에 물 채워 조심조심 옮기다 결국 바닥에 찰랑찰랑 흘림","merit":"뭘 나르든 크게 쏟거나 깨뜨릴 일이 없음"},{"strength":5,"text":"리모컨 찾으려 온 집을 뒤졌는데 결국 내 엉덩이 밑에 깔려 있음","merit":"잃어버린 물건이 늘 생각보다 가까운 데서 나옴"},{"strength":6,"text":"계란후라이 예쁘게 뒤집으려는 순간 노른자가 퍽 터짐","merit":"요리에 실패해도 맛은 늘 그럭저럭 괜찮게 나옴"},{"strength":7,"text":"카드에 글씨 예쁘게 다 쓰고 마지막 글자에 펜 똥이 나와 번짐","merit":"웬만해선 글씨가 깔끔하게 잘 써짐"},{"strength":8,"text":"하얀 옷에 커피 튀어 물티슈로 문질렀더니 얼룩이 더 넓게 번짐","merit":"옷에 뭐가 묻어도 대개 자국 없이 잘 지워짐"},{"strength":9,"text":"급하게 지퍼 올리다 안쪽 천이 씹혀 올라가지도 내려가지도 않음","merit":"옷·가방 지퍼가 좀처럼 고장 나지 않음"},{"strength":10,"text":"라면 물 완벽하게 맞춰 다 끓였는데 봉지에 수프가 없어 끼니를 망침","merit":"요리하면 대개 필요한 재료가 딱 맞게 갖춰져 있음"}]},"b":{"name":"타이밍 현타","emoji":"⏱️","penalties":[{"strength":2,"text":"1분이라도 더 자고 싶은데 알람 울리기 딱 1분 전에 저절로 눈뜸","merit":"늦잠으로 지각할 일은 좀처럼 없음"},{"strength":3,"text":"택배 왔다는 문자에 신나서 현관문 열었는데 옆집 택배임","merit":"내 택배는 늘 감쪽같이 안전하게 도착함"},{"strength":4,"text":"방금 떠오른 엄청 기발한 생각을 1초 만에 하얗게 까먹음","merit":"정작 중요한 약속·할 일은 절대 안 까먹음"},{"strength":5,"text":"영수증 버려달라 했는데 직원이 이미 내 빵 봉투에 넣어버림","merit":"산 물건이 늘 깔끔하게 잘 포장돼 나옴"},{"strength":6,"text":"바쁘게 움직이는데 이어폰 줄이 문고리·주머니에 걸려 홱 빠짐","merit":"이어폰 줄이 엉키거나 한 짝을 잃어버릴 일이 없음"},{"strength":7,"text":"뛰어가면 탈 수 있을 줄 알았던 엘리베이터 문이 코앞에서 닫힘","merit":"대개 엘리베이터가 도착하는 타이밍에 딱 맞게 옴"},{"strength":8,"text":"일기예보 믿고 무거운 우산 챙겨 나왔는데 하루 종일 쨍쨍함","merit":"정작 갑자기 비 올 땐 늘 우산이 손에 있음"},{"strength":9,"text":"꽉 막혀 옆 차선으로 바꿨더니 원래 있던 차선이 뻥 뚫림","merit":"급할 땐 신기하게 내가 탄 쪽이 먼저 풀림"},{"strength":10,"text":"큰맘 먹고 정가 주고 산 물건이 바로 다음 날 반값 세일에 뜸","merit":"정작 꼭 필요한 건 늘 세일 타이밍에 딱 걸림"}]},"resultCards":{"a":{"extreme":{"label":"다시 하면 되지 하며 묵묵히 도로 작업하는 헛수고파"},"mild":{"label":"매번 도로아미타불은 서러운데 그러려니 하는 헛수고파"}},"b":{"extreme":{"label":"한 끗 차이 억울해도 운은 따른다 믿는 타이밍파"},"mild":{"label":"놓친 건 아까운데 다음 기회 노리는 타이밍파"}}}}'::jsonb, true, (select coalesce(max(sort),0)+1 from decks), now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;

-- body-device (신규 덱 · v3 일상현타 · 2026-07-13)
insert into decks (id, title, emoji, data, is_public, sort, updated_at)
values ('body-device', '내 몸이 배신 vs 내 기기가 배신', '😖', '{"id":"body-device","title":"내 몸이 배신 vs 내 기기가 배신","icon":"😖","type":"attribute","a":{"name":"몸 현타","emoji":"🤕","penalties":[{"strength":2,"text":"시원하게 하품하는데 옆 사람이 말 걸어 중간에 뚝 끊김","merit":"웬만해선 졸리거나 나른할 일이 없음"},{"strength":3,"text":"밥 맛있게 먹다 안쪽 볼살을 강하게 콱 씹음","merit":"무얼 먹어도 좀처럼 체하지 않음"},{"strength":4,"text":"눈 비볐다 빠진 속눈썹이 눈알에 딱 붙어 아무리 씻어도 안 나옴","merit":"눈에 뭐가 들어가도 대개 금방 저절로 빠짐"},{"strength":5,"text":"맨발로 걷다 문지방·식탁 다리에 새끼발가락을 정통으로 찧음","merit":"어디 부딪혀도 멍이 잘 안 들고 금방 가심"},{"strength":6,"text":"배고파서 뜨거운 국물 허겁지겁 먹다 입천장이 홀랑 까짐","merit":"뜨거운 음식을 먹어도 좀처럼 입천장을 데지 않음"},{"strength":7,"text":"오래 앉았다 일어서는데 다리가 저려 휘청하며 몇 초 굳어 있음","merit":"오래 앉아·서 있어도 다리가 잘 안 붓고 안 저림"},{"strength":8,"text":"양치 못 한 채 마스크 쓰면 내 입 냄새가 코로 고스란히 되돌아옴","merit":"웬만해선 입냄새·체취 걱정 없이 산뜻함"},{"strength":9,"text":"고기 구워 먹고 나오면 머리카락부터 속옷까지 냄새가 다 뱀","merit":"웬만한 냄새는 하룻밤 자고 나면 싹 빠짐"},{"strength":10,"text":"중요한 발표·소개팅마다 하필 그때 몸이 배신함(꼬르륵·딸꾹질·재채기 폭발)","merit":"긴장되는 자리에서도 손발에 땀이 안 나고 목소리가 안 떨림"}]},"b":{"name":"기기 현타","emoji":"📱","penalties":[{"strength":2,"text":"화면 캡처하려다 볼륨 버튼만 눌러 화면 정중앙에 볼륨 바가 뜸","merit":"정작 찍고 싶은 순간은 늘 제때 잘 찍힘"},{"strength":3,"text":"유튜브 스킵 누르려다 광고 자체를 눌러 앱스토어 팝업이 뜸","merit":"중요한 링크·버튼은 늘 한 번에 정확히 눌림"},{"strength":4,"text":"자동완성이 엉뚱한 단어로 바꿔 그대로 전송돼 버림","merit":"내가 보낸 메시지는 오해 없이 딱 내 의도대로 전달됨"},{"strength":5,"text":"한참 고민해 새 비밀번호 쳤는데 이전과 같다고 튕김","merit":"정작 중요한 비번·계정은 절대 안 잊어버림"},{"strength":6,"text":"하필 중요한 순간에만 와이파이·데이터가 뚝뚝 끊김","merit":"정작 급할 땐 인터넷이 끊김 없이 빵빵하게 터짐"},{"strength":7,"text":"카톡 1은 계속 안 사라지는데 상대 인스타엔 스토리가 새로 올라옴","merit":"정작 중요한 연락은 늘 제때 답이 옴"},{"strength":8,"text":"사람 많은 개찰구에서 하필 교통카드가 미승인으로 막혀 뒤가 밀림","merit":"계산·결제가 늘 한 번에 매끄럽게 됨"},{"strength":9,"text":"저장 안 한 작업물이 앱이 갑자기 튕기며 통째로 날아감","merit":"중요한 파일은 절대 안 날아가고 늘 자동 저장돼 있음"},{"strength":10,"text":"아침에 눈뜨면 밤새 충전기가 헐거워 폰이 3%로 방전돼 있음","merit":"급할 때 충전기·보조배터리가 늘 손 닿는 곳에 있음"}]},"resultCards":{"a":{"extreme":{"label":"몸이 하필 그때 배신해도 웃어넘기는 몸현타파"},"mild":{"label":"매번 몸이 삐끗해 서러운데 그러려니 하는 몸현타파"}},"b":{"extreme":{"label":"기기가 배신해도 다시 켜면 그만이라는 기기현타파"},"mild":{"label":"디지털 삽질은 억울한데 툴툴대며 버티는 기기현타파"}}}}'::jsonb, true, (select coalesce(max(sort),0)+1 from decks), now())
on conflict (id) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  data = excluded.data,
  updated_at = excluded.updated_at;
